### ISSUE TITLE
增加「flamingo」——mac的改键映射，宏软件

### ISSUE THREAD

**Issue by drinktoomuchsax** [jaywcjlove/awesome-mac#1020]
NOTE: Each discrete (stand-alone) request should be in its own issue.

**Put "Add ____" as Title**
 [x] Done

**Provide a link to the proposed addition.**
[Place link here.](https://openfibers.github.io/flamingo/README_cn)

**Explain why it should be added**
买了鼠标和新的宏键盘，打造自己的工作流的时候在清单里没找到这种改键的软件，一般大家都用的是Keyboard Maestro，但是就功能来说，这款可以免费使用的flamingo和keboard masetro基本上没有差别，就是使用门槛要高一点点（需要会javascript的语法

**Additional context**
![截屏2022-02-18 00 26 54](https://user-images.githubusercontent.com/87611896/154525581-272d54ef-0d70-4af1-a04d-43b1b6ac68a4.png)
  
![截屏2022-02-18 00 26 18](https://user-images.githubusercontent.com/87611896/154526089-4ec32422-2c6a-4c6a-8495-b49b2149324e.png)

[这里](https://openfibers.github.io/flamingo/help_cn)有详细的如何使用，总的来说还是比较好用的

### Issue Checklist

Put an x in the boxes once you've completed each step. You can also fill these out after creating the issue. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before responding to the issue.

- [x] I have checked for other similar issues
- [x] I have explained why this change is important
- [x] I have added necessary documentation (if appropriate)

**Comment by suliveevil** [comment]
都是用 JSON 配置，为什么不试试 Karabiner-Elements 呢，老牌开源软件，我的 macOS 上最不可或缺的 app。

**Comment by suliveevil** [comment]
Keyboard Maestro 可以搭配 Karabiner-Elements 使用，而不是互相取代的关系。

我建议将映射交给 KE，将快捷键交给 KM，这样 KE 给了你把不可编程键盘变成可编程键盘的能力，KM 给了你可视化管理快捷键的能力。

**Comment by suliveevil** [comment]
如果想要大而全，Hammerspoon 是个好选择。
