### ISSUE TITLE
中英文同步问题

### ISSUE THREAD

**Issue by xcv58** [jaywcjlove/awesome-mac#104]
@jaywcjlove 有没有考虑过这么问题？

**Comment by jaywcjlove** [comment]
考虑过，有好的解决方案？

**Comment by xcv58** [comment]
感觉目前用 Markdown 的情况下并没有很好的方案。

我在想可不可以用一种方法把多语言的翻译集中在一起进行管理。譬如说源码中是这种格式：

```
[AppNmae](link) - [中文介绍][Description]
```

然后在显示的时候自动隐藏不需要的介绍内容。譬如选中文，就可以把别的语言的简介隐藏掉。这样至少列表的顺序是统一的。别人提交 Pull Request 的时候也方便添加别的语言的 TODO。

还有一种方法是用固定的列表来显示，然后把不同语言的简介放到单独的文件里。渲染的时候在根据语言的不同去读取。

这些想法都需要 js 和修改当前的格式，感觉太重了。但维护起来应该会比现在方便很多，而且还可以增加一下功能，譬如排序、按免费收费过滤之类的。

**Comment by jaywcjlove** [comment]
我想过这么干，可以设计一个json 文件维护，通过js生产出Markdown或者是HTML，https://jaywcjlove.github.io/awesome-mac/   这个就是通过js 生成出来的。

**Comment by xcv58** [comment]
同意你的看法，好处是有序，只是直接修改 json 文件也比较麻烦。

**Comment by xcv58** [comment]
我想应该可以用 node.js 写一个小程序。直接把 json 文件都出来然后可以本地渲染成 html 页面预览和修改。然后再写回 json 文件。同时可以生成不同语言的 markdown 文件。

**Comment by jaywcjlove** [comment]
这样同样有维护成本！pull requests 都是markdown 修改的内容，需要你指定他们修改data.json文件。

**Comment by xcv58** [comment]
我的意思是维护的时候可以直接运行 `node.js` 在浏览器中修改。小程序本身来维护 json 与 markdown 文件。但是一样的成本很高。

**Comment by jaywcjlove** [comment]
这样 更麻烦，我们运维方便，人家还要安装nodejs

**Comment by xcv58** [comment]
或者直接做成 online 的。需要 pull request 的流程：

1. 登录网站，点击按钮增加 App 与相应语言的简介。(如果不懂中文就在相应的地方自动加 TODO)
2. 在网站上下载对应的 json （也可能不需要） 与 markdown 文件。
3. 覆盖本地文件，commit, push, pull request

**Comment by jaywcjlove** [comment]
不用高这么复杂吧，目前的维护还行。支持多国语言就是，可以用hexo.io 搭建网站。总得运维一个库的。

**Comment by xcv58** [comment]
hexo.io 都不需要用，直接用 GitHub Page 就可以 deploy 了，毕竟咱们自己不需要数据库之类的东西，数据就是 json 文件，所有其他的东西都用 react+js 在浏览器中做。

主要是值不值得做这个。如果不考虑 UI 的话，我一个周末应该就可以写出来。

**Comment by jaywcjlove** [comment]
目前我觉得不值得这么做。

**Comment by xcv58** [comment]
恩，确实有点复杂。

**Comment by alichtman** [comment]
Is `hexo.io` being suggested as an addition?

**Comment by xcv58** [comment]
Thanks @alichtman for suggestions!

I think the problem is how can we make sure the English and Chinese versions are synced without the hassle. A static or dynamic website doesn't matter for the problem. Could you please tell me if there is a feature in `hexo.io` that can solve the problem?

FYI, @jaywcjlove has a repo for desktop App of the list: https://github.com/jaywcjlove/amac

**Comment by jaywcjlove** [comment]
**Awesome Mac App for macOS**. Installers for the latest stable build for Mac can be [downloaded here](https://github.com/jaywcjlove/amac/releases).

[![Get it on macOS](http://jaywcjlove.github.io/sb/download/macos.svg)](https://github.com/jaywcjlove/amac/releases)
