### ISSUE TITLE
Please, add Pinegrow Web Editor

### ISSUE THREAD

**Issue by batsteek** [jaywcjlove/awesome-mac#108]
http://pinegrow.com/
http://pinegrow.com/pinegrow-atom.html
http://pinegrow.com/wordpress-theme-builder.html

Thanks ;)

**Comment by jaywcjlove** [comment]
I do not like this software! you can case a vote. like this...  👍  👎

**Comment by alichtman** [comment]
In almost 2 years, this got only one community +1.

Closing.
