### ISSUE TITLE
Add MailMate

### ISSUE THREAD

**Issue by privaterra** [jaywcjlove/awesome-mac#1115]
NOTE: Each discrete (stand-alone) request should be in its own issue.

**Put "Add ____" as Title**
 [X] Done

**Provide a link to the proposed addition.**
[MailMate](https://freron.com).

**Explain why it should be added**
MailMate is an IMAP email client for macOS featuring extensive keyboard control, Markdown integrated email composition, advanced search conditions and drill-down search links, equally advanced smart mailboxes, automatic signature handling, cryptographic encryption/signing (OpenPGP and S/MIME), tagging, multiple notification methods, alternative message viewer layouts including a widescreen layout, flexible integration with third party applications, and [much more](https://manual.mailmate-app.com/).

**Additional context**

### Issue Checklist

Put an x in the boxes once you've completed each step. You can also fill these out after creating the issue. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before responding to the issue.

- [X] I have checked for other similar issues
- [X] I have explained why this change is important
- [X] I have added necessary documentation (if appropriate)

**Comment by ColoursofOSINT** [comment]
Please close, @jaywcjlove.
