### ISSUE TITLE
Remove FruitJuice

### ISSUE THREAD

**Issue by danickblouin** [jaywcjlove/awesome-mac#1118]
NOTE: Each discrete (stand-alone) request should be in its own issue.

**Put "Remove ____" as Title**
 [x ] Done

**Explain why it should be removed**
FruitJuice is no longer available for purchase as of April 17th, 2022.

**Additional context**
Message on their [website](http://fruitjuiceapp.com/): 
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/45211997/194418963-914f0bd5-f752-4623-82c8-711d508fb3f4.png">

**Comment by jaywcjlove** [comment]
@danickblouin thx!
