### ISSUE TITLE
Multiple links are broken (respond with status code 404)

### ISSUE THREAD

**Issue by ndsvw** [jaywcjlove/awesome-mac#1131]
**The Readme.md file contains multiple broken hyperlinks. They all respond with status code 404:**
  - [x] http://www.eigenlogik.com/spectrum/mac → Status: 404
  - [x] http://www.litixsoft.de/english/mms/ → Status: 404
  - [x] https://apps.apple.com/us/app/journey-diary-journal/id1265425422?mt=12 → Status: 404
  - [x] https://arguiot.com/Chirper/ → Status: 404
  - [x] https://bitbucket.org/kosovan/theunarchiver → Status: 404
  - [x] https://bitbucket.org/mamburu/cog/ → Status: 404
  - [x] https://coffeeboo.itch.io/sweeper → Status: 404
  - [x] https://itunes.apple.com/app/cellist/id897814548 → Status: 404
  - [x] https://itunes.apple.com/app/gifox-gif-recording-and-sharing/id1082624744 → Status: 404
  - [x] https://itunes.apple.com/app/id1207744923 → Status: 404
  - [x] https://itunes.apple.com/app/jpegmini-lite/id525742250 → Status: 404
  - [x] https://itunes.apple.com/app/loremify/id1028877632 → Status: 404
  - [x] https://itunes.apple.com/app/navicat-data-modeler-essentials-visual-database-designer/id532423082 → Status: 404
  - [x] https://itunes.apple.com/app/spectrum/id518156125?mt=12 → Status: 404
  - [x] https://itunes.apple.com/de/app/assetizr/id1449126727?l=en&mt=12 → Status: 404
  - [x] https://itunes.apple.com/us/app/better-rename-9/id414209656 → Status: 404
  - [x] https://itunes.apple.com/us/app/dashlane-password-manager/id552383089 → Status: 404
  - [x] https://itunes.apple.com/us/app/lyricsx/id1254743014?mt=12 → Status: 404
  - [x] https://itunes.apple.com/us/app/pixel-perfect/id916097243 → Status: 404
  - [x] https://itunes.apple.com/us/app/screenshot-psd/id489880259 → Status: 404
  - [x] https://itunes.apple.com/us/app/surge-web-developer-tool-proxy/id1040100637 → Status: 404
  - [x] https://itunes.apple.com/us/app/tincta/id448340648 → Status: 404
  - [x] https://netbeans.org/community/sources/ → Status: 404
  - [x] https://smallcubed.com/mt/ → Status: 404

**Comment by jaywcjlove** [comment]
@ndsvw Fix done
