### ISSUE TITLE
More broken links

### ISSUE THREAD

**Issue by ndsvw** [jaywcjlove/awesome-mac#1132]
**The Readme.md file contains multiple broken hyperlinks. There are different problems (site not reachable, site does not exist, certificate expired, status codes >= 500, ...):**
  - [x] http://vanilla.matthewpalmer.net → Status: Other problem
  - [x] http://www.aegisub.org/ → Status: Other problem
  - [x] http://www.controlplaneapp.com/ → Status: 502
  - [x] http://zythum.sinaapp.com/youkuhtml5playerbookmark/ → Status: 603
  - [x] https://apps.apple.com/en/app/noteplan-3/id1505432629 → Status: 500
  - [x] https://chocolatapp.com/ → Status: Other problem
  - [x] https://codinn.com/products/ssh-tunnel/ → Status: Other problem
  - [x] https://colorpicker.crea-th.at → Status: Other problem
  - [x] https://coolantformac.com → Status: Other problem
  - [x] https://grayscalemode.com/ → Status: Other problem
  - [x] https://mouseless.app/ → Status: Other problem
  - [x] https://musicplus.io → Status: Other problem
  - [x] https://www.lmms.io → Status: Other problem

**Comment by jaywcjlove** [comment]
@ndsvw thx!
