### ISSUE TITLE
Unofficial Instagram Desktop App

### ISSUE THREAD

**Issue by jaywcjlove** [jaywcjlove/awesome-mac#114]
https://github.com/terkelg/ramme

**Comment by alichtman** [comment]
I'd consider adding a `Social Media` section and throw this and FB Messenger for Mac under that, as well as a Twitter GUI and some other stuff. idk

**Comment by jaywcjlove** [comment]
@alichtman This is a good practice

**Comment by alichtman** [comment]
See #357. Going to close this for now.
