### ISSUE TITLE
Bug in Simplified Chinese edition: Typora is not a free software

### ISSUE THREAD

**Issue by AStogov** [jaywcjlove/awesome-mac#1175]
In README-zh.md, Simplified Chinese edition, Typora is marked as a "free to use" software.

But **Typora** is not a free-to-use software. It offers 15 days free trial and after trial you should purchase for a licence.

However, if you do not purchase, you could still use it, with a notice of "not activated". 

I suggest removing "free to use" mark of Typora in Chinese edition.

**Comment by jaywcjlove** [comment]
@AStogov It has been modified
