### ISSUE TITLE
Add Orion Browser

### ISSUE THREAD

**Issue by KyleErhabor** [jaywcjlove/awesome-mac#1180]
**Put "Add ____" as Title**
- [x] Done

**Provide a link to the proposed addition.**
https://browser.kagi.com

**Explain why it should be added**
Orion is a browser built on [WebKit](https://webkit.org) that largely mimicks Safari's user interface while adding more features, such as support for Chrome extensions and Firefox add-ons, zero telemetry by default, vertical tabs, etc. While still in beta, it's a nice drop-in replacement for Safari with more features.

**Additional context**
Orion was created by the people who work on the [Kagi](https://kagi.com/) search engine.

### Issue Checklist

- [x] I have checked for other similar issues
- [x] I have explained why this change is important
- [x] I have added necessary documentation (if appropriate)

**Comment by sdee3** [comment]
Orion was added to the list in https://github.com/jaywcjlove/awesome-mac/pull/1182
