### ISSUE TITLE
窗口管理工具和Markdown编辑器推荐

### ISSUE THREAD

**Issue by nfang** [jaywcjlove/awesome-mac#119]
推荐一款窗口管理工具 [SizeUp](http://www.irradiatedsoftware.com/sizeup/) 和一款Markdown编辑器 [Marxico](https://marxi.co/)。Marxico可以和Evernote同步，对于用Evernote记笔记的同学应该是蛮有用的。

**Comment by jaywcjlove** [comment]
[Marxico](https://marxi.co/)  看起来不错的样子

**Comment by xcv58** [comment]
[CMD Markdown](https://www.zybuluo.com/) 也很好的，可惜只有中文。而且作者近期内没有开发英文的计划。

**Comment by nfang** [comment]
@jaywcjlove 嗯，就是如果不需要和Evernote联动的话alternative就很多了。

**Comment by S1ngS1ng** [comment]
Marxico确实好用
不过，如果不用 EverNote，其实选择大把

窗口管理，我在英文版里已经加了 SizeUp 和 Divvy。还有 HammerSpoon。
github.com/S1ngS1ng/HammerSpoon
自己写的 HammerSpoon 配置。比 SizeUp 多一个调窗口大小的功能。其他基本一致

**Comment by alichtman** [comment]
Included:

1. SizeUp
2. Marxico instead of CMD Markdown for aesthetic and functionality reasons.
3. Hammerspoon

Closing this issue.
