### ISSUE TITLE
English?

### ISSUE THREAD

**Issue by rafaelamorim** [jaywcjlove/awesome-mac#12]
Hello there,

this seems pretty interesting, but it's in Chinese :/

can you guys please translate to english?

best.

**Comment by jaywcjlove** [comment]
@rafaelamorim I'm English is very bad! The work is not complete for the time being.

**Comment by rafaelamorim** [comment]
So let's leave this issue open until a fellow Chinese user can help us out ;)

best

**Comment by jaywcjlove** [comment]
👌

**Comment by so77id** [comment]
👍

**Comment by lfarah** [comment]
👍

**Comment by yPangXie** [comment]
@rafaelamorim I am going to provide the English version for this repo during this weekend, since my English is a piece of s**t... Hope you can check it before merging.

**Comment by rafaelamorim** [comment]
Thanks man!
No worries, I'll check your PR.

**Comment by xcv58** [comment]
Hi, @yPangXie probably we can work together.

**Comment by xcv58** [comment]
This is my unfinished English version: https://github.com/xcv58/awesome-mac/blob/master/README-en.md

**Comment by yPangXie** [comment]
@xcv58 It's awesome😎

**Comment by jaywcjlove** [comment]
👍

**Comment by xcv58** [comment]
@jaywcjlove 已经完成了 编辑器 部分的翻译。你可不可以考虑一下先 merge 一次，这样方便和其他人协作翻译。

**Comment by gitzhou** [comment]
Hi there, i may give some translation work for this repo, where show i start.
@yPangXie  @xcv58 @jaywcjlove

**Comment by jaywcjlove** [comment]
@gitzhou [README-en](https://github.com/jaywcjlove/awesome-mac/blob/master/README-en.md)  Here look. 

你自己选择一块儿翻译就可以了现在只有 @yPangXie 在从上到下翻译。

**Comment by yPangXie** [comment]
补充, @xcv58 也在翻译中~

**Comment by gitzhou** [comment]
@yPangXie @jaywcjlove 好的 晚上先翻一下看看 英语一般 😂

**Comment by xcv58** [comment]
@yPangXie @gitzhou Do you guys have Google Drive access? If yes, we can create a Google doc to collaborate together. So that we can avoid duplicated work.

**Comment by gitzhou** [comment]
Yes, i can access Google Drive @xcv58

**Comment by yPangXie** [comment]
@xcv58 Me too, I can access to Google Drive.

**Comment by xcv58** [comment]
Great! Please use this doc: https://docs.google.com/document/d/1IP14AYCescLBkiSI4yvTBdlSBz7mIu7NvZSsXrBV8NI/edit?usp=sharing

@yPangXie @gitzhou

**Comment by gitzhou** [comment]
Yes, i will directly edit this google docs. It's more convenient

**Comment by yPangXie** [comment]
@xcv58 @gitzhou @seandou @iawia002 [https://docs.google.com/document/d/1IP14AYCescLBkiSI4yvTBdlSBz7mIu7NvZSsXrBV8NI/edit?usp=sharing](https://docs.google.com/document/d/1IP14AYCescLBkiSI4yvTBdlSBz7mIu7NvZSsXrBV8NI/edit?usp=sharing) google drive上刚刚同步了最新的英文版([pr 39](https://github.com/jaywcjlove/awesome-mac/pull/39))

**Comment by xcv58** [comment]
@yPangXie 非常感谢！我今天出去 hiking 了，晚上会再翻译一些。

**Comment by gitzhou** [comment]
我先翻了两部分，加了一个科学上网的vpn推荐，drive上也同步更新了
已经提交了 #47 
@yPangXie  @xcv58  @jaywcjlove

**Comment by S1ngS1ng** [comment]
@yPangXie @xcv58 @jaywcjlove @gitzhou 
PR已经提交，还没弄完。。刚弄到Reading and Writing那里。求review，求建议

**Comment by jiangzhouq** [comment]
👍

**Comment by S1ngS1ng** [comment]
@jaywcjlove 家里断网。。没法弄了。。我争取周日下午弄一下。。TAT

**Comment by ryanmaclean** [comment]
I'm happy to help with the English! I've gone through an initial scan, will submit a bigger PR later today.

**Comment by S1ngS1ng** [comment]
PR #86  Second Commit. Review and update before `##Web and Browsers`

**Comment by S1ngS1ng** [comment]
PR #88 Final Commit. Everything is done.

**Comment by TheGermanGuy** [comment]
If you are using chrome, google translate would help!!!

**Comment by xcv58** [comment]
@TheGermanGuy Actually the English translation is done. Please visit https://github.com/jaywcjlove/awesome-mac/blob/master/README-en.md

**Comment by xcv58** [comment]
@jaywcjlove 是不是应该关闭这个 issue 了？
