### ISSUE TITLE
Please add Dashlane

### ISSUE THREAD

**Issue by johannlaqua** [jaywcjlove/awesome-mac#122]
https://www.dashlane.com/en/
Really good password management on desktop and mobile.

**Comment by MrsJLane** [comment]
For what, I might ask?

**Comment by primerproyecto** [comment]
Maybe this repo is just for applications and tools for developers and designers. :-)

**Comment by BirkhoffLee** [comment]
Dashlane has a VERY poor support, I don't recommend it though it has a really beautiful UI.

**Comment by alichtman** [comment]
Due to the reported poor development support, and lacking customer service, I don't think we should add `Dashlane`. I'd like to have only *exceptionally secure* apps on the Password Manager list. It does have a beautiful UI, though. Closing for now.
