### ISSUE TITLE
Remove RememBear

### ISSUE THREAD

**Issue by echoapus** [jaywcjlove/awesome-mac#1228]
NOTE: Each discrete (stand-alone) request should be in its own issue.

**Put "Remove ____" as Title**
 [ ] Done

**Explain why it should be removed**
A clear and concise description of why it should be added to this list.

RememBear will be available to download and use for existing users until January 1, 2024. 

**Additional context**

**Comment by jaywcjlove** [comment]
- https://github.com/jaywcjlove/awesome-mac/pull/423
