### ISSUE TITLE
Broken hyperlinks

### ISSUE THREAD

**Issue by ndsvw** [jaywcjlove/awesome-mac#1254]
Hello, I found some broken hyperlinks:
- [x] https://apps.apple.com/en/app/noteplan-3/id1505432629 (file: README.md, status code: 500)
- [x] https://apps.apple.com/us/app/proxie/id897814548 (file: README.md, status code: 404)
- [x] http://pixologic.com/sculptris/# (file: README.md, error: CERT_HAS_EXPIRED)
- [x] https://fbmacmessenger.rsms.me/ (file: README.md, error: ECONNRESET)
- [x] https://www.codeux.com/textual (file: README.md, error: ECONNRESET)
- [x] https://www.sodaplayer.com/ (file: README.md, error: ENOTFOUND)
- [x] https://itunes.apple.com/app/type2phone-bluetooth-keyboard/id472717129 (file: README.md, status code: 404)
- [x] https://getmanta.app/ (file: README.md, error: ECONNRESET)
- [x] https://masterbuilders.io (file: README.md, error: ECONNRESET)
- [x] https://apps.apple.com/us/app/clovery-for-google-apps/id1552618413 (file: README.md, status code: 404)
- [x] https://removex.io (file: README.md, error: ECONNRESET)

**Comment by jaywcjlove** [comment]
- [x] https://apps.apple.com/en/app/noteplan-3/id1505432629 **can visit**
- [x] ~~https://apps.apple.com/us/app/proxie/id897814548 (file: README.md, status code: 404)~~
- [x] ~~http://pixologic.com/sculptris/# (file: README.md, error: CERT_HAS_EXPIRED)~~
- [x] ~~https://fbmacmessenger.rsms.me/ (file: README.md, error: ECONNRESET)~~
- [x] https://www.codeux.com/textual (file: README.md, error: ECONNRESET)
- [x] ~~https://www.sodaplayer.com/ (file: README.md, error: ENOTFOUND)~~
- [x] ~~https://itunes.apple.com/app/type2phone-bluetooth-keyboard/id472717129 (file: README.md, status code: 404)~~
- [x] ~~https://getmanta.app/ (file: README.md, error: ECONNRESET)~~
- [x] https://masterbuilders.io (file: README.md, error: ECONNRESET)
- [x] ~~https://apps.apple.com/us/app/clovery-for-google-apps/id1552618413 (file: README.md, status code: 404)~~
- [x] ~~https://removex.io (file: README.md, error: ECONNRESET)~~

@ndsvw thx!

**Comment by Gugobush** [comment]
g
