### ISSUE TITLE
🎉 Add PrettyClean

### ISSUE THREAD

**Issue by ethan0924** [jaywcjlove/awesome-mac#1263]
### 🪩 Provide a link to the proposed addition

https://www.prettyclean.cc/zh

### 😳 Explain why it should be added

简洁好用的`Mac`磁盘清理工具。

### 🧨 Issue Checklist

- [X] I have checked for other similar issues
- [X] I have explained why this change is important
- [X] I have added necessary documentation (if appropriate)

**Comment by jaywcjlove** [comment]
@imtsy thx!
