### ISSUE TITLE
🎉 Add Default Folder X

### ISSUE THREAD

**Issue by smomop** [jaywcjlove/awesome-mac#1274]
### 🪩 Provide a link to the proposed addition

https://www.stclairsoft.com/DefaultFolderX/index.html

### 😳 Explain why it should be added

Track recently used files and folders in every app
Reopen recently closed Finder windows
Copy and Move files in file dialogs

### 📖 Additional context

![AnnotatedOpenDialog@2x](https://github.com/jaywcjlove/awesome-mac/assets/63437136/75ddfe9a-2a95-47a9-a3ec-8acb10d258e5)

### 🧨 Issue Checklist

- [X] I have checked for other similar issues
- [X] I have explained why this change is important
- [X] I have added necessary documentation (if appropriate)

**Comment by ColoursofOSINT** [comment]
Done @jaywcjlove
