### ISSUE TITLE
🎉 Add Linear mouse

### ISSUE THREAD

**Issue by imtsy** [jaywcjlove/awesome-mac#1278]
### 🪩 Provide a link to the proposed addition

https://linearmouse.app/zh-CN/

### 😳 Explain why it should be added

自定义鼠标和触控板的指针，和滚动方向。

### 🧨 Issue Checklist

- [X] I have checked for other similar issues
- [X] I have explained why this change is important
- [X] I have added necessary documentation (if appropriate)

**Comment by ColoursofOSINT** [comment]
Please close this issue.
