### ISSUE TITLE
🎉 Add Lima

### ISSUE THREAD

**Issue by joske** [jaywcjlove/awesome-mac#1289]
### 🪩 Provide a link to the proposed addition

https://github.com/lima-vm/lima

### 😳 Explain why it should be added

Easily and quickly startup VMs (using QEMU under the hood). Can even be used as docker engine (without having to use docker desktop app): see https://itnext.io/replace-docker-desktop-with-lima-88ec6f9d6a19.

### 🧨 Issue Checklist

- [X] I have checked for other similar issues
- [X] I have explained why this change is important
- [X] I have added necessary documentation (if appropriate)

**Comment by ColoursofOSINT** [comment]
Done https://github.com/jaywcjlove/awesome-mac/pull/1312
