### ISSUE TITLE
🎉 Add Mullvad VPN

### ISSUE THREAD

**Issue by ColoursofOSINT** [jaywcjlove/awesome-mac#1292]
### 🪩 Provide a link to the proposed addition

https://github.com/jaywcjlove/awesome-mac#security-tools

### 😳 Explain why it should be added

Apps for Mullvad are open source, (https://github.com/mullvad/mullvadvpn-app). Add open source label to them. I will submit a pull request in a bit. 

### 🧨 Issue Checklist

- [X] I have checked for other similar issues
- [X] I have explained why this change is important
- [X] I have added necessary documentation (if appropriate)

**Comment by ColoursofOSINT** [comment]
Whoops, forgot to change the title.

**Comment by jaywcjlove** [comment]
@ColoursofOSINT Welcome to submit a PR

**Comment by ColoursofOSINT** [comment]
Done: https://github.com/jaywcjlove/awesome-mac/pull/1299
