### ISSUE TITLE
🎉 Add Obsisian

### ISSUE THREAD

**Issue by fishel-feng** [jaywcjlove/awesome-mac#1313]
### 🪩 Provide a link to the proposed addition

https://obsidian.md/

### 😳 Explain why it should be added

Obsidian is the private and flexible writing app that adapts to the way you think.

### 🧨 Issue Checklist

- [X] I have checked for other similar issues
- [X] I have explained why this change is important
- [X] I have added necessary documentation (if appropriate)

**Comment by ColoursofOSINT** [comment]
Obsidian is already added.

**Comment by fishel-feng** [comment]
sorry, I just check the CN readme. It seems to be several versions behind.
