### ISSUE TITLE
推荐一个数据库管理软件

### ISSUE THREAD

**Issue by silence0201** [jaywcjlove/awesome-mac#132]
Datum一款很不错的Sqlite3数据库管理软件

**Comment by xcv58** [comment]
链接： http://datumapps.com/datum.html

**Comment by jaywcjlove** [comment]
@silence0201  已添加..  https://github.com/jaywcjlove/awesome-mac/commit/9486a25126c6986b443fa5be754a3d20ba3f1fea

**Comment by silence0201** [comment]
添加的地址有错吧

**Comment by jaywcjlove** [comment]
thx!
