### ISSUE TITLE
保持gitHub在线工具

### ISSUE THREAD

**Issue by silence0201** [jaywcjlove/awesome-mac#133]
[Trailer](https://github.com/ptsochantaris/trailer)
保持Github在线 包括iOS/OSX客户端

**Comment by xcv58** [comment]
说实话，没看懂这 App 是什么作用。

**Comment by silence0201** [comment]
实时查看github关注的状态

**Comment by jaywcjlove** [comment]
没有查看github趋势榜的吗？ https://github.com/trending

**Comment by silence0201** [comment]
这只是查看issue和一些通知的工具
