### ISSUE TITLE
🗑 Remove NightOwl

### ISSUE THREAD

**Issue by DeanFoley** [jaywcjlove/awesome-mac#1346]
### 🪩 Provide a link to the proposed addition

N/A

### 😳 Explain why it should be removed

There are two chief reasons to remove NightOwl from the list of Awesome MacOS applications:

1. The functionality is now baked into MacOS, and has been since Mac OS Catalina ([source](https://support.apple.com/en-gb/guide/mac-help/mchl52e1c2d2/mac))
2. The NightOwl application was, at some point, acquired by another company. It now seems to be unavailable for download on the main website, and is not available via Homebrew.

### 📖 Additional context

Posting this purely in the interest of research: a Reddit post [alleges that NightOwl is used as part of a botnet for market research](https://old.reddit.com/r/MacOS/comments/14kdhz7/psa_the_nightowl_application_was_bought_out_and/).

**Comment by DeanFoley** [comment]
Also I think the "remove entry" issue template needs updating 😅

**Comment by jaywcjlove** [comment]
> Also I think the "remove entry" issue template needs updating 😅

@DeanFoley  Welcome to PR! Modify `.github/ISSUE_TEMPLATE/REMOVE_ITEM_FROM_LIST.yml` file.

https://github.com/jaywcjlove/awesome-mac/blob/6c81209372bbb750c3da183084adb43398e258dc/.github/ISSUE_TEMPLATE/REMOVE_ITEM_FROM_LIST.yml?plain=1#L1-L32

**Comment by DeanFoley** [comment]
I'd be delighted! Thank you for the quick turnaround on my issue 😊
