### ISSUE TITLE
Server Log Parsing

### ISSUE THREAD

**Issue by rovo79** [jaywcjlove/awesome-mac#136]
Any recommendations for mac tools that parse Server Logs?

**Comment by jaywcjlove** [comment]
This can have @rovo79

**Comment by xcv58** [comment]
@rovo79 What's your goal for parsing Server Logs?

If you mean the log from macOS system itself.
I personally feel /Applications/Utilities/Console.app is good enough.

If not, could you please tell use the log source, goal, etc.?

**Comment by rovo79** [comment]
I sometimes download my server access logs to my local machine and use something like Piwik to analyze the logs.

**Comment by xcv58** [comment]
I have no idea for this. I usually use Vim/Python to do similar things.

**Comment by brianluby** [comment]
I would recommend taking a look at Lnav.  http://lnav.org  This is not mac specific but accomplishes what you are looking to do.  As a plus it can be installed via homebrew.  

A very handy item with LNav is the ability to import the logs to SQLite and analyze them via lnav in SQLite.  You can also do SQL queries straight against the logs.  This is reminiscent of a log analysis tool I heavily used in the past called logparser from Microsoft.  

How this helps.

**Comment by jaywcjlove** [comment]
@brianluby  This is very cool.

**Comment by alichtman** [comment]
Lnav was added. Closing issue.
