### ISSUE TITLE
Add Tauri in Frameworks For Hybrid Applications section

### ISSUE THREAD

**Issue by rafaeldcf** [jaywcjlove/awesome-mac#1377]
### 🪩 Provide a link to the proposed addition

https://github.com/tauri-apps/tauri

### 😳 Explain why it should be added

Tauri (https://tauri.app/) is a tool to create cross platform applications like Electron. 

### 🧨 Issue Checklist

- [X] I have checked for other similar issues
- [X] I have explained why this change is important
- [X] I have added necessary documentation (if appropriate)

**Comment by jaywcjlove** [comment]
@rafaeldcf This is not an application
