### ISSUE TITLE
QQ输入法已经下线了Mac版，所以可以从列表里移除了。

### ISSUE THREAD

**Issue by depthsky2016** [jaywcjlove/awesome-mac#139]
如题，QQ输入法已经下线了Mac版，应该是并入了搜狗输入法里了。

**Comment by bapuqln** [comment]
并没有并入


发自网易邮箱大师
在2016年09月16日 10:31，depthsky2016 写道:

如题，QQ输入法已经下线了Mac版，应该是并入了搜狗输入法里了。

**Comment by depthsky2016** [comment]
在网页上是看不到了，莫非是在憋大招？

**Comment by jaywcjlove** [comment]
能憋啥大招？@depthsky2016

**Comment by bapuqln** [comment]
别想大招了，不维护了


发自网易邮箱大师
在2016年09月16日 15:34，小弟调调™ 写道:

能憋啥大招？@depthsky2016
