### ISSUE TITLE
🗑 Remove Free Download Manager

### ISSUE THREAD

**Issue by maliayas** [jaywcjlove/awesome-mac#1402]
### 😳 Explain why it should be removed

Free Download Manager is a shady application. From [Wikipedia](https://en.wikipedia.org/wiki/Free_Download_Manager):

> It was found that the website freedownloadmanager.org was spreading Linux malware for over three years until 2022. Researchers discovered that the site was intermittently redirecting users to domains that served a malicious version of the Free Download Manager software. This malware included a script that installed a backdoor on Linux devices to steal passwords, browsing history, cryptocurrency wallet files, and cloud service credentials. The infection was uncovered in September 2023 though it had been active since 2020. It is believed to have been a supply chain attack impacting the legitimate Free Download Manager project. The malware went undetected for years due to the stealthy nature of Linux threats compared to Windows. The administrators of the site did not respond to notifications about the campaign.

**Comment by jaywcjlove** [comment]
@maliayas thx!
