### ISSUE TITLE
Hi  this is chris the data you been copying from me  for over 8 years never introduce yourself never let me know who you are and why are you fucking with me to top it off you write some bullshit on the computer that you took over mike

### ISSUE THREAD

**Issue by Chrisbronson** [jaywcjlove/awesome-mac#1436]
MacBook without letting me know 
And wrote a note in there saying I am using your software so please do me a favor I know it's you or your friends fucking remove the software I never lodge it to put it in in the first
 
You work for Apple I don't know what you're doing but I never allowed you to log into my computers and always change my settings

**Comment by jaywcjlove** [comment]
@Chrisbronson What ?
