### ISSUE TITLE
🎉 Add x-cmd

### ISSUE THREAD

**Issue by lunrenyi** [jaywcjlove/awesome-mac#1447]
### 🪩 Provide a link to the proposed addition

https://github.com/x-cmd/x-cmd

### 😳 Explain why it should be added

**x-cmd is a toolset implemented using posix shell and awk.**
It's very small. In the new system environment, it can help me quickly obtain the various tools I need and set up the environment. 

### 📖 Additional context

It is very small in size and offers many interesting features. Here is a milestone demo: https://x-cmd.com/

**Tools Provided by x-cmd:**
    - [Wrappers for Common Commands (e.g., cd, ip, ps, tar, apt, brew)](https://x-cmd.com/mod/zuz): These wrapped commands are more intelligent and easier to use compared to the native commands.
    - [Lightweight Package Management Tool](https://x-cmd.com/pkg/): We have implemented a lightweight package management tool using shell and awk. Through it, you can quickly obtain most common software tools, such as jq, 7za, bat, nvim, python, node, go, etc.
  - [CLI for Useful Websites (e.g., github.com, cht.sh)](https://x-cmd.com/mod/cht): We have wrapped their APIs using shell and awk for daily use and to obtain corresponding services in scripts.
  - [AI Tools](https://x-cmd.com/mod/openai): We provide CLIs for ChatGPT, Gemini, Jina.ai, etc., and have wrapped corresponding shortcut commands for different application scenarios, such as `@gemini` for chatting with Gemini AI and `@zh` for using AI to translate specified content or command results.

### 🧨 Issue Checklist

- [X] I have checked for other similar issues
- [X] I have explained why this change is important
- [X] I have added necessary documentation (if appropriate)

**Comment by jaywcjlove** [comment]
fix #1448
