### ISSUE TITLE
🎉 Add Logseq

### ISSUE THREAD

**Issue by ExDevilLee** [jaywcjlove/awesome-mac#1457]
### 🪩 Provide a link to the proposed addition

https://logseq.com/

### 😳 Explain why it should be added

免费好用的双向链笔记工具

### 🧨 Issue Checklist

- [X] I have checked for other similar issues
- [X] I have explained why this change is important
- [X] I have added necessary documentation (if appropriate)

**Comment by Qifull** [comment]
@jaywcjlove This issue has been resolved. Could you please close it?
Thanks!
