### ISSUE TITLE
🐞 Bug Report: xxx.md

### ISSUE THREAD

**Issue by ChristinWhite** [jaywcjlove/awesome-mac#1468]
### 🐞 Describe the bug

The [Hummingbird app](https://hummingbirdapp.site/) website listed seems to be dead now. I'm not sure if they just changed the domain or if it's a different app altogether, but there's a repo for a Hummingbird window manager [here](https://github.com/finestructure/Hummingbird) which links to this [homepage](https://hbird.app/). I did notice it's been three years since any code was a code commit, a year since the readme was updated.

### 📖 Expected behavior

The listed site to be live and correct.

### 🌅 Screenshots

![CleanShot 2024-08-26 at 11 44 28@2x](https://github.com/user-attachments/assets/dbfa90b3-a2ff-4fbf-b505-a6ccce56758e)

**Comment by jaywcjlove** [comment]
I see the author is very active on GitHub and still addresses issues in the Hummingbird repository, so I've fixed the incorrect link. @ChristinWhite thx!
