### ISSUE TITLE
🎉 Add Lots of apps

### ISSUE THREAD

**Issue by WHMyyds** [jaywcjlove/awesome-mac#1515]
### 🪩 Provide a link to the proposed addition

1.[AI 0x0 🤖️](https://github.com/mushan0x0/AI0x0.com)
2.[Wox](https://github.com/Wox-launcher/Wox)
3.[Tran](https://github.com/Borber/Tran)
4.[pear-rec(github)](https://github.com/027xiguapi/pear-rec)
5.[Alist](https://alist.nn.ci/)
[Alist(github)](https://github.com/alist-org/alist)
6.[downkyicore](https://github.com/yaobiao131/downkyicore)

### 😳 Explain why it should be added

1.一个多模态多模型通用型的全能 AI 查询生成桌面悬浮助手应用，支持 MacOS 和 Windows，可在任意桌面软件使用 AI 能力。
2.Wox is a cross-platform launcher that simply works. It's an alternative to Alfred and Launchy
3.简洁, 快速, 划词翻译
4.pear-rec(pear rec) is a free and open-source cross-Platform screenshot, screen recording, audio recording, and video recording software.
5.🗂️A file list program that supports multiple storages, powered by Gin and Solidjs
6.基于哔哩下载姬Windows版和AvaloniaUI制作的跨平台版本(支持Windows、linux、macOS)。

### 📖 Additional context

❤️❤️❤️

### 🧨 Issue Checklist

- [X] I have checked for other similar issues
- [X] I have explained why this change is important
- [X] I have added necessary documentation (if appropriate)

**Comment by jaywcjlove** [comment]
@WHMyyds Recommend one at a time.

**Comment by WHMyyds** [comment]
okay
