### ISSUE TITLE
关于你的SVG图标

### ISSUE THREAD

**Issue by S1ngS1ng** [jaywcjlove/awesome-mac#152]
你好。我看到你的另一个 repo 里面有些 Badge 的 svg 图标。

https://github.com/jaywcjlove/sb

我把其中的[两个](https://github.com/jaywcjlove/sb/tree/gh-pages/lang)用在了我自己的 repo 里面。

请问可以么？

**Comment by jaywcjlove** [comment]
@S1ngS1ng 可以的

**Comment by S1ngS1ng** [comment]
好的。十分感谢 🙏
