### ISSUE TITLE
Please add Paragon NTFS

### ISSUE THREAD

**Issue by Revod** [jaywcjlove/awesome-mac#156]
Paragon NTFS for Mac® 14 is fully compatible with Apple’s new security policy ensuring fast, hassle-free and safe access to NTFS partitions from macOS 10.12 Sierra.
Once the program is installed, the user can get started right away: conveniently navigate contents and read, edit, copy or create files and folders. The driver guarantees advanced support of NTFS file systems and provides fast and transparent read/write access to any NTFS partition under macOS 10.12.

https://www.paragon-software.com/home/ntfs-mac/

![volumes](https://cloud.githubusercontent.com/assets/10109689/20493335/ae9ab19c-afee-11e6-99e6-80c7cf9b4c59.png)

**Comment by jaywcjlove** [comment]
@Revod 
[Mounty](http://enjoygineering.com/mounty/) for NTFS is available for free.
