### ISSUE TITLE
🎉 Add downkyicore

### ISSUE THREAD

**Issue by WHMyyds** [jaywcjlove/awesome-mac#1563]
### 🪩 Provide a link to the proposed addition

https://github.com/yaobiao131/downkyicore

### 😳 Explain why it should be added

基于哔哩下载姬Windows版和AvaloniaUI制作的跨平台版本(支持Windows、linux、macOS)。
开发这个版本目的是由于开发者日常使用macOS，当想下载up视频是偶然间发现了哔哩下载姬Windows版，发现很好用，就是不能支持macOS使用，就基于AvaloniaUI重新开发了一个跨平台版本。

### 🧨 Issue Checklist

- [X] I have checked for other similar issues
- [X] I have explained why this change is important
- [X] I have added necessary documentation (if appropriate)

**Comment by WHMyyds** [comment]
cloud you please tell me why you don't consider addingit to your list?

**Comment by jaywcjlove** [comment]
@WHMyyds Added to the Chinese list.

**Comment by WHMyyds** [comment]
so other software i recommended all added to the Chinese list?
