### ISSUE TITLE
建议删除盗版发布网站链接

### ISSUE THREAD

**Issue by Justineo** [jaywcjlove/awesome-mac#17]
最好的抵制，是不要给他们导流。

**Comment by yPangXie** [comment]
感觉意义不大.. 倒不如亮出来, 让人知道这些站点上盗版软件比较多, 谨慎下载.

**Comment by jaywcjlove** [comment]
赞同 @yPangXie 只能抵制，这种网站一搜一大把。我们只能抵制，但是抵制得有目标，抵制谁。

**Comment by Justineo** [comment]
@yPangXie 谨慎下载？你是不是在逗我啊，这叫抵制啊……

@jaywcjlove 一搜一大把那还得搜不是，你现在都列出来，不是降低了犯罪的成本？你自己是可以抵制，但能保证这个项目不起到给这些网站导流的效果？

**Comment by jaywcjlove** [comment]
@Justineo 我们不能掩耳盗铃，列出来，告诫不要盗版下载，然后这个即使是导流，应该会引起相关大软件公司注意，去走法律途径....

如果你视而不见，他们会活得很好的。

**Comment by yPangXie** [comment]
@Justineo 你以为那些用着盗版却不知羞耻的, 靠提高这么点儿下载盗版软件的成本就能抵制的了? 
都不用扯"做了总比不做强"这种话, 是删掉或不删掉基本没什么意义..

谨慎下载是说下的软件搞不好是被人插了后门的.. 告诫的不是那些恬不知耻的盗版软件使用者, 是给那些用着盗版, 但心存愧疚人一个提醒. 这票人还有救.

**Comment by jaywcjlove** [comment]
找那么多开源软件和免费软件，是劝告大家，即使你很穷也是有选择，

列出黑名单，是有一些人下载的软件以为自己下载的是正规途径下载，

来源百度
```
现在维权和正版软件消费意识也越来越强了
1、学习有关知识产权保护的法律，掌握识别盗版制品的知识。
2、坚持购买、使用正版书刊、音像制品、电脑软件和正牌商品。
3、主动劝阻家人亲友不购买、不使用盗版制品，不阅读、不传播盗版读物。
4、积极举报制作、贩卖盗版制品和其他侵犯商标权、著作权的行为。
```

3、主动劝阻，你们这些网站被列入黑名单了，你们得小心了

**Comment by Justineo** [comment]
既然 owner 是这个意见，那我多说无益了。

**Comment by jaywcjlove** [comment]
这个issue开着吧，大家一起讨论说不定后面，讨论结果是另外一个结果呢

**Comment by hqpko** [comment]
我也建议删掉

**Comment by xcv58** [comment]
支持列出来。因为即使是删掉，找出这些网站的成本是很低的。列在这里至少有如下的好处：

1. 明确我们反对盗版的态度
2. 警示他人勿下载可能含有 后门/木马 的软件
3. 可以给予这些网站的所有者压力

**Comment by azad112358** [comment]
建议去掉这些网站的跳转功能，这样点了也不会跳转导流

**Comment by yPangXie** [comment]
@azad112358 啊，这个不错~ 支持

**Comment by jaywcjlove** [comment]
@azad112358 好建议先采纳了😄 ，奇技淫巧啊

**Comment by S1ngS1ng** [comment]
@jaywcjlove 
这个才是istat menus的官网，istat menus本身是收费的。。https://bjango.com/mac/istatmenus/

不想花钱有免费版的可以用：https://bjango.com/mac/istatmini/

**Comment by yPangXie** [comment]
@S1ngS1ng 可以直接提个PR

**Comment by jaywcjlove** [comment]
@S1ngS1ng 已经更新，  c7c85c5635612268809df2297234c2001443bb11

**Comment by zhujianvar** [comment]
反对盗版，把你们正版win，adobe亮出来。

**Comment by Justineo** [comment]
@zhujianvar 序列号怎么能拿给你看，老贵了。

**Comment by YohannFree** [comment]
@zhujianvar  所以换了mac，而且并不用adobe 。
flash除外，可是flash是免费的 啊哈哈哈~

**Comment by jaywcjlove** [comment]
用Sketch 便宜点

**Comment by LYPanda** [comment]
不好意思，用了太多盗版软件，买过的正版软件也就几个（都不超过50），好多正版都太贵了，动不动就是几百而且大版本更新又得重新买。伤不起啊。

**Comment by spitz1jwq** [comment]
学生党表示虽然想用正版，但.......

**Comment by yhyangjiabin8504** [comment]
**其实正版和盗版在中国要看个人,然后才是法律。我们国家的法律对这个方面很缺失**

**Comment by steven0lisa** [comment]
不如联系一下软件服务商，提供一下活动或者优惠码，这样子会好不少。很多人都愿意购买软件，但没什么门路。

**Comment by flowstone** [comment]
史蒂芬周的博客， http://www.sdifen.com

**Comment by dreamsparkx** [comment]
https://nmac.to

**Comment by jaccobhagare** [comment]
thanks or solving such a big issue and nobody solves that kind of problems such as [IDM Serial Key](https://hdlicense.com/idm-crack/) and total server issues with complete merger repositeries because these days good work is precious.

**Comment by thomas8618** [comment]
Thanks for sharing such an amazing article. 
https://premiumcrack.com/solid-explorer-file-manager-pro-unlocked-apk/

**Comment by jaccobhagare** [comment]
[AutoCAD Crack Version](https://keygensoft.com/autodesk-autocad-crack/) Download has a flexible subscription model with new features available with each release and product update for instance. Moreover, If you have a perpetual license for AutoCAD 2016 or earlier, the following changes have been made to AutoCAD 2017, AutoCAD 2018, AutoCAD 2019, and AutoCAD 2020. Downloaded from

**Comment by jaccobhagare** [comment]
> 收入和产品价格 决定 是否要购买正版
> 不是所有盗版者都喜欢去使用盗版
> 一棒子打死是不对的
> 正版能接受的范围内 我会选择正版 如果价格太离谱我只能说 我心有余而力不足 只能盗版

[AutoCAD Crack Version](https://whitecrack.com/autocad-crack/) Download has a flexible subscription model with new features that are available with every version and every product update, for example. If you have a perpetual license for AutoCAD 2016 or earlier, the following changes have been made to AutoCAD 2017, AutoCAD 2018, AutoCAD 2019, and AutoCAD 2020.

**Comment by jaccobhagare** [comment]
[AutoCAD Crack Version](https://thiscrack.com/autodesk-autocad-crack-license-key/) has a flexible subscription model with new features that are available with every version and every product update, for example. If you have a perpetual license for AutoCAD 2016 or earlier, the following changes have been made to AutoCAD 2017, AutoCAD 2018, AutoCAD 2019, and AutoCAD 2020.

**Comment by jaccobhagare** [comment]
> @jaywcjlove istat那个链接。。好像不太对。
> 这个才是istat menus的官网，istat menus本身是收费的。。https://bjango.com/mac/istatmenus/
> 
> 不想花钱有免费版的可以用：https://bjango.com/mac/istatmini/
> @jaywcjlove istat那个链接。。好像不太对。
> 这个才是istat menus的官网，istat menus本身是收费的。。https://bjango.com/mac/istatmenus/
> 
> 不想花钱有免费版的可以用：https://bjango.com/mac/istatmini/
> @jaywcjlove istat那个链接。。好像不太对。
> 这个才是istat menus的官网，istat menus本身是收费的。。https://bjango.com/mac/istatmenus/
> 
> 不想花钱有免费版的可以用：https://bjango.com/mac/istatmini/

[refx Nexus crack](https://vst-torrent.com/refx-nexus-crack/) has a 32-stage arpeggiator with note conversion, a 32-stage trance gate, an Hall licensed by Arts Acoustic and a sophisticated modulation matrix with which you can shape the sound. Nexus includes a comprehensive 4GB library of over 880 sounds controlled by a friendly in-house librarian to find just the sound you need in the heat of the creative moment. Functions such as search, favorites and categorization are standard not only in the factory library, but in all available extensions. 
> @jaywcjlove istat那个链接。。好像不太对。
> 这个才是istat menus的官网，istat menus本身是收费的。。https://bjango.com/mac/istatmenus/
> 
> 不想花钱有免费版的可以用：https://bjango.com/mac/istatmini/

**Comment by jaccobhagare** [comment]
> 收入和产品价格 决定 是否要购买正版
> 不是所有盗版者都喜欢去使用盗版
> 一棒子打死是不对的
> 正版能接受的范围内 我会选择正版 如果价格太离谱我只能说 我心有余而力不足 只能盗版

[iZotope Neutron Advanced Crack](https://pluginstorrents.com/izotope-neutron-advanced-crack-mac/) Modern-to-Neutron Three, Blend Assistant, research your song and give recommendations on track grade in seconds. View a full list of your tracks with izotope IPC plug-ins, choose a focused detail for your mix, and let the Mix Assistant concentrate for your tune find an ultimate place in less time than ever before You can start with your mix.

**Comment by HoodyGif** [comment]
[TunesKit iPhone data recovery Crack](https://yellowcrack.com/tuneskit-iphone-data-recovery-crack-with-serial-key/) that makes Tuneskit iPhone data healing proud of all the iOS stats recovery answers is the fastest recovery of misplaced and deleted files on iPhone, iPad and iPod touch. You may get back all the missing records for your iOS devices with the easiest 3 simple steps: select information recovery mode, scan and preview the lost records, select the files you want and improve them.

**Comment by HoodyGif** [comment]
[SoundPad Crack ](https://twitcrack.com/soundpad-crack/) finds its way into virtual headphones / earphones looks like a normal media player. Just play sounds for your interlocutor. Play sounds through speakers and microphone. This is the default when playing sounds by double-clicking or using a keyboard shortcut. You can set up keyboard shortcuts for each sound so that they play quickly and easily when playing full screen games. If the microphone is making noise, this option is for you. Instead of adding sound to the microphone signal, it replaces the signal so that your friends can hear the sound with the quality of the source. Find sounds faster with the search bar.

**Comment by Masui142** [comment]
thanks for sharing this beautiful article  https://crackabout.com/gta-v-crack/

**Comment by Masui142** [comment]
Its great platform.Thanks for sharing <a href="https://crackabout.com/idm-download/">sharing</a>

**Comment by license111** [comment]
This website really has all of the info I needed concerning this subject.<a href="https://licensedaily.com/freemake-video-converter-crack/" title= "freemake">freemake</a>

**Comment by worldforcrack** [comment]
> @Justineo 你以为那些用着盗版却不知羞耻的, 靠提高这么点儿下载盗版软件的成本就能抵制的了? 都不用扯"做了总比不做强"这种话, 是删掉或不删掉基本没什么意义..
> 
> 谨慎下载是说下的软件搞不好是被人插了后门的.. 告诫的不是那些恬不知耻的盗版软件使用者, 是给那些用着盗版, 但心存愧疚人一个提醒. 这票人还有救.

i have launched new softwares check once
<a href="https://worldforcrack.com/smadav-key/">samdav-2019-key</a>
<a href="https://worldforcrack.com/crack-filmora/">crack-filmora-9-download</a>
<a href="https://worldforcrack.com/nord-vpn-cracked-apk/">nord-vpn-cracked-apk</a>
<a href="https://worldforcrack.com/corel-draw-x-portable/">corel-draw-x5-portable</a>
<a href="https://worldforcrack.com/ccleaner-pro-key/">cclraner-pro-key-v5-crack</a>
<a href="https://worldforcrack.com/idm-portable-crack/">idm-portable-crack-v6</a>
<a href="https://worldforcrack.com/gta-v-latest-crack/">gta-v-latest-file-full</a>
<a href="https://worldforcrack.com/uad-plugins-crack/">uad-pulgins-crack-ultimate</a>
<a href="https://worldforcrack.com/winrar-latest-version-crack/">winrar-latest-version</a>

**Comment by worldforcrack** [comment]
> thanks for sharing this beautiful article https://crackabout.com/gta-v-crack/

there are some new softwares available for mac, check once
<a href="https://worldforcrack.com/smadav-key/">samdav-2019-key</a>
<a href="https://worldforcrack.com/crack-filmora/">crack-filmora-9-download</a>
<a href="https://worldforcrack.com/nord-vpn-cracked-apk/">nord-vpn-cracked-apk</a>
<a href="https://worldforcrack.com/corel-draw-x-portable/">corel-draw-x5-portable</a>
<a href="https://worldforcrack.com/ccleaner-pro-key/">cclraner-pro-key-v5-crack</a>
<a href="https://worldforcrack.com/idm-portable-crack/">idm-portable-crack-v6</a>
<a href="https://worldforcrack.com/gta-v-latest-crack/">gta-v-latest-file-full</a>
<a href="https://worldforcrack.com/uad-plugins-crack/">uad-pulgins-crack-ultimate</a>
<a href="https://worldforcrack.com/winrar-latest-version-crack/">winrar-latest-version</a>

**Comment by license111** [comment]
Thanks for sharing us a great information that is actually helpful. <a href="https://licensedaily.com/vray-4-crack/" title= "vray">vray</a>

**Comment by license111** [comment]
Usually I never used to comment on sites but your article is so convincing that I never stop myself to say something good about it. You are doing a great job. <a href="https://licensedaily.com/iboysoft-data-crack/" title= "iboysoft">iboysoft</a>

**Comment by xcv58** [comment]
@jaywcjlove we should lock this issue.
