### ISSUE TITLE
为何没有看到网易云音乐和Evernote笔记？

### ISSUE THREAD

**Issue by perry2008084** [jaywcjlove/awesome-mac#170]

**Comment by jaywcjlove** [comment]
网易云音乐，这些个云，都感觉像是个  网页浏览器....😀

加上也无妨

**Comment by perry2008084** [comment]
在线听一些歌还是蛮方便，还有一些歌单直接听:)

**Comment by alichtman** [comment]
Evernote is in the README. Closing this.

(As best I understand, this is taken care of. I ran the Chinese through Google Translate so I kind of understand what you guys said.)
