### ISSUE TITLE
做了个开源的图床工具 fu，望收录

### ISSUE THREAD

**Issue by klesh** [jaywcjlove/awesome-mac#172]
项目地址：https://github.com/klesh/fu

支持通过 sftp 上传
支持自定义格式
目前支持 imgur.com 和 sm.ms 图床

**Comment by jaywcjlove** [comment]
可以github弄个官网哦。 我先研究研究

**Comment by yPangXie** [comment]
`macOS`的`v1.1.0`版下载链接404了

**Comment by klesh** [comment]
@yPangXie 已修复

**Comment by alichtman** [comment]
Added to new `File Sharing` category
