### ISSUE TITLE
macOS Sierra 10.12.3系统下，Black Screen 不支持 zsh 的 cd 命令？

### ISSUE THREAD

**Issue by wangshuaibing** [jaywcjlove/awesome-mac#176]
macOS Sierra 10.12.3系统下，Black Screen 貌似不支持 zsh 的 cd 命令，其他的还没有发现，不知道是我的个例，还是真的存在 bug

**Comment by xcv58** [comment]
那你应该去 https://github.com/vshatskyi/black-screen 提 issue 吧。
