### ISSUE TITLE
给 awesome-mac 项目写了一个用户脚本，可以按类型过滤

### ISSUE THREAD

**Issue by dofy** [jaywcjlove/awesome-mac#178]
写了一个 awesome-mac 用户脚本，可以按 **免费**，**热门**，**开源** 等类型过滤内容。

脚本 Gist 地址： https://gist.github.com/dofy/4ac64114b32acc9e6ffa6024c2302124

如果你装了Tampermonkey 之类的插件，点击 `raw` 按钮应该可以直接安装。

![image](https://cloud.githubusercontent.com/assets/344197/23983525/8201cbbe-0a4f-11e7-9d7f-c5e9e3b6a810.png)

![image](https://cloud.githubusercontent.com/assets/344197/23983541/a3cfc836-0a4f-11e7-8b89-24aedc8dde18.png)

**Comment by jaywcjlove** [comment]
@dofy 打不开你的脚本

**Comment by dofy** [comment]
@jaywcjlove 脚本就是 GitHub 上的 Gist 啊，这个是 UserScript，得先安装插件。

**Comment by SunWeihan** [comment]
Safari+tampermonkey，装了没有效果呀_(:з」∠)_

**Comment by dofy** [comment]
@SunWeihan safari 好像确实有问题，暂时还不确定是什么导致的，Chrome 和 Firefox 没问题。

**Comment by alichtman** [comment]
Closing this b/c all are either: 

+ Not relevant
+ Merged already
