### ISSUE TITLE
是不是可以增加一个changelog，这样方便老用户来查看更新

### ISSUE THREAD

**Issue by depthsky2016** [jaywcjlove/awesome-mac#182]
时不时会来看看，但是不知道最近添加了什么以及有什么变化，是不是可以添加一个changelog，比如最近添加了什么软件及最近删除了什么软件之类的。

**Comment by jaywcjlove** [comment]
不是你需要什么软件就这里搜索的吗？

**Comment by jetablezhu** [comment]
不错




发自网易邮箱大师
在2017年03月23日 14:36，depthsky2016 写道：

时不时会来看看，但是不知道最近添加了什么以及有什么变化，是不是可以添加一个changelog，比如最近添加了什么软件及最近删除了什么软件之类的。

**Comment by jaywcjlove** [comment]
打tag？出log?

**Comment by zhaochunqi** [comment]
请使用 watch 功能。

**Comment by TomShine** [comment]
@zhaochunqi watch功能是可以，但是要是有个changlog似乎更好呀 😀
