### ISSUE TITLE
推荐一个自己写的Mac中漂亮的代码行计算工具(已开源)--PPRows

### ISSUE THREAD

**Issue by jkpang** [jaywcjlove/awesome-mac#188]
PPRows -- 在Mac上计算你写了多少行代码
开源地址: https://github.com/jkpang/PPRows

1. 支持检测参与计算的代码文件夹数量以及代码行数;
2. 支持同时检测多文件/多文件夹代码;
3. 支持自定义检测的文件类型,例如:c,swift,oc, java....类型的代码文件;
4. 支持自定义需要忽略检测的文件夹, 例如: iOS工程中的Pods文件夹;
5. 支持中文与英文,跟随系统语言变化
6. 支持忽略代码中的空行, 代码行数计算更精确.
### 望收录~~~
![gif1](https://cloud.githubusercontent.com/assets/17583451/24613781/e36f4c9e-18bb-11e7-8a75-5c2f7e4dbfeb.gif)
![gif2](https://cloud.githubusercontent.com/assets/17583451/24613792/eaff693a-18bb-11e7-8537-3bbf86c77073.gif)

**Comment by jaywcjlove** [comment]
thx!
