### ISSUE TITLE
推荐 Ulysses

### ISSUE THREAD

**Issue by taufook** [jaywcjlove/awesome-mac#192]
优秀的 Markdown 写作软件

**Comment by TomShine** [comment]
挺好的，就是有点贵，我感觉还是国产NWeb好用😀

**Comment by ernestyao** [comment]
附议，刚想进来补充这个呢，原来已经有写了
支持iA Writer的focus模式，支持直接发布Wordpress等，也能通过外部代码支持laTEX
最重要是颜值高

**Comment by CarolHsu** [comment]
+1 👍
