### ISSUE TITLE
为什么 Mou 还在这个表单上…不应该被除名吗

### ISSUE THREAD

**Issue by hackape** [jaywcjlove/awesome-mac#198]
How is it awesome?

**Comment by xiyouMc** [comment]
Mou 在最新MacOS上已经不支持了。 没有及时跟进更新。
建议使用 MacDown

**Comment by nightsailer** [comment]
Mou is a cheater!

**Comment by jaywcjlove** [comment]
Mou ever great!

**Comment by alichtman** [comment]
Mou is in the repo. Closing

**Comment by excitedcat** [comment]
Mou 涉嫌欺诈骗钱，建议移除该应用。而且该应用无法在新系统上使用。

Mou is suspected of fraudulently defrauding and recommends removing the app. And this app cannot be used on new macOS.

@alichtman
