### ISSUE TITLE
Mac软件下载

### ISSUE THREAD

**Issue by BBcaptain** [jaywcjlove/awesome-mac#2]
* Best Free Apps For Mac - Xclient.info: http://xclient.info/

**Comment by jaywcjlove** [comment]
添加上去了

**Comment by yifanchen** [comment]
https://github.com/zeit/hyperterm
https://github.com/tmux/tmux

**Comment by jaywcjlove** [comment]
@yifanchen hyperterm 这个是啥看上去很酷的样子

我已经添加上来了

**Comment by yifanchen** [comment]
Terminal, JavaScript, html, css写的
