### ISSUE TITLE
Add CoconutBattery

### ISSUE THREAD

**Issue by ernestyao** [jaywcjlove/awesome-mac#204]
Gemini是macpaw家的，他们家几个小软件都还挺好用。G的主要作用就是搜索你选的目录，提示出其中重复的文件，并让你选择删除其中一个或多个；也可以配置自动删除的规则（如果有明确规则的话 :P ）

A Better Finder Rename目前大版本是10，MAS里有，作用是文件批量重命名，当然可以写脚本，但是ABFR已经做到很好用了，又是GUI，可以预览效果，对目录、文件、子目录里都可以用。

coconutBattery也是个专注的小工具，就是电池信息，和系统信息里最大的不同是你可以记录下某天的情况，方便你关注电池寿命，它的网站上还能帮你做个曲线。现在也支持iOS了（需要连到电脑）。

最后，两个无损播放软件，这俩应该是这个领域内的主流选择之一了：Audirvana Plus和Amarra。后者正在做大版本更新。

**Comment by S1ngS1ng** [comment]
无损播放器，我在用 VOX。也还不错的。https://vox.rocks/mac-music-player

**Comment by alichtman** [comment]
Suggested additions: 

1. VOX - https://vox.rocks/mac-music-player
1. coconut Battery

**Comment by alichtman** [comment]
@ernestyao Open a PR to add coconutBattery.
