### ISSUE TITLE
Incorrect Link for Homebrew Casks

### ISSUE THREAD

**Issue by dingwilson** [jaywcjlove/awesome-mac#215]
Under the section [Third-Party App Markets](https://github.com/jaywcjlove/awesome-mac#third-party-app-markets), the link for `Homebrew Cask` incorrectly links to `caskroom.io`. The correct link is [caskroom.github.io](http://caskroom.github.io).

**Comment by jaywcjlove** [comment]
[Third-Party App Markets](https://github.com/jaywcjlove/awesome-mac#third-party-app-markets)  what's the problem?

**Comment by dingwilson** [comment]
`Homebrew Cask`的链接是不正确的。 应该是[caskroom.github.io](caskroom.github.io).

**Comment by jaywcjlove** [comment]
thx.
