### ISSUE TITLE
推荐：命令行工具 — autojump

### ISSUE THREAD

**Issue by ttop5** [jaywcjlove/awesome-mac#226]
⚡️ 懒人必备，从此告别又臭又长的路径名，一键直达任何目录。[https://github.com/wting/autojump](https://github.com/wting/autojump)

**Comment by TomShine** [comment]
这个可以作为 `oh-my-zsh`的插件使用，效果更好

**Comment by ttop5** [comment]
@TomShine 对的，我就是这么用的，很酸爽。

**Comment by Kenshinhu** [comment]
其实还有一个是 Z 的
