### ISSUE TITLE
推荐代理(翻墙)工具 v2ray

### ISSUE THREAD

**Issue by XGHeaven** [jaywcjlove/awesome-mac#227]
这个软件我感觉非常可以用来替代shadowsocks，首先功能强大，不仅仅支持ss/ssr协议，而且支持socks，http等常用协议，而且vmess协议更好用。非常方便的支持各种混淆，还有动态端口，多路复用，端口转发。底层协议支持tcp/udp/mkcp等

[官网](https://www.v2ray.com/)

**Comment by lanan-docs** [comment]
试一试 蓝岸V2ray  http://lanan.me/
