### ISSUE TITLE
vienna rss link is dead

### ISSUE THREAD

**Issue by sturobson** [jaywcjlove/awesome-mac#228]
Hey, 

Going through the list I found the link to vienna rss -- www.vienna-rss.org -- is dead.

I'd love to make a PR to fix this, but I'm unsure of you steps to create the README.md files. Happy to edit that and PR if that's cool :)

**Comment by rubenvarela** [comment]
The README.md is a text file that is processed using a markdown parser.

Here is a Github guide on Markdown, https://guides.github.com/features/mastering-markdown/. 

To edit it, you can use any text editor. Another option, after forking, you should have an option to edit the file on your browser ![screen shot](https://cloud.githubusercontent.com/assets/3499097/24909187/e4d6d3ba-1e90-11e7-83b5-fa8d7fd24569.png)
