### ISSUE TITLE
关于搜索问题

### ISSUE THREAD

**Issue by KyoChou** [jaywcjlove/awesome-mac#233]
比如我只想看必备的软件, 现在是图标, 不能搜索. 可不可以优化一下

**Comment by jaywcjlove** [comment]
@KyoChou I was trying to make an application to solve the search problem.

**Comment by KyoChou** [comment]
OK. thx.

**Comment by dofy** [comment]
@KyoChou 可以试试这个脚本 #178

**Comment by jaywcjlove** [comment]
#237 A crazy plan is in progress.

**Comment by 13-64** [comment]
Q�Q*J,�OK+N-Q�263

**Comment by MoneyMouthBottom** [comment]
Nice
