### ISSUE TITLE
A tool to show Mac caps lock status.  [Captin] 大小写提示工具推荐

### ISSUE THREAD

**Issue by nylqd** [jaywcjlove/awesome-mac#248]
推荐[Captin](http://captin.strikingly.com/)
A tool to show Mac caps lock status.

多种提示方式：Dock，Menu Bar or HUD
Multiple Ways of Notifications, Both Visual and Acoustic

一个免费工具，而且作者针对用户的反馈能够及时反馈和修改，开发效率很高

**Comment by jaywcjlove** [comment]
@nylqd 禁不起历练，24天就打不开了。
