### ISSUE TITLE
Retinizer 这个很666

### ISSUE THREAD

**Issue by yanhaijing** [jaywcjlove/awesome-mac#254]
http://www.pc6.com/mac/112430.html

**Comment by jaywcjlove** [comment]
@yanhaijing 这个早期软件，现在几乎找不到不支持Retina屏幕的应用了。

**Comment by yanhaijing** [comment]
@jaywcjlove 比如 git自带的gitk 😶

**Comment by jaywcjlove** [comment]
这个看上去很拽的样子 是这个吗？ https://www.gitkraken.com/ 
 @yanhaijing

**Comment by alichtman** [comment]
Read through discussion and closing.
