### ISSUE TITLE
推荐一个聚合类通讯软件 Rambox

### ISSUE THREAD

**Issue by ymqy** [jaywcjlove/awesome-mac#258]
简介：开源免费，支持很多服务
网址：http://rambox.pro/

**Comment by ymqy** [comment]
麻烦给个原因，下次还要推荐其他软件呢

**Comment by jaywcjlove** [comment]
@ymqy 已经添加进去了

![image](https://user-images.githubusercontent.com/1680273/29072459-43c675aa-7c7a-11e7-83f9-7ddb8c74dd5c.png)

**Comment by ymqy** [comment]
好的୧(๑•̀⌄•́๑)૭
