### ISSUE TITLE
Tooltip text on icon hover?

### ISSUE THREAD

**Issue by bookwormgirl910** [jaywcjlove/awesome-mac#259]
Given that there are a number of different icons and that their meanings aren't immediately obvious, I think it would be helpful to add tooltip text (in addition to the existing `alt` text) when readers hover over the icons for each recommendation.

From what I understand, this can be achieved in Markdown by adding by adding "Title" after the link, as in the following example.

`[![Open-Source Software][OSS Icon]](https://github.com/atom/atom "Open-source software")`
`![Freeware][Freeware Icon "Freeware"]`
`![hot][hot Icon "Hot"]`
`![Recommend][tuijian Icon "Recommend"]`
`![must-have][bibei Icon "Must have"]`

**Comment by jaywcjlove** [comment]
@bookwormgirl910  Okay, I'll try it!
