### ISSUE TITLE
This repository is not included in the Awesome project

### ISSUE THREAD

**Issue by bennettyuan18** [jaywcjlove/awesome-mac#269]
Did you know [Awesome macOS](https://github.com/iCHAIT/awesome-macOS)?
Why you don't go there to commit PRs?
Or commit PR to [Awesome project](https://github.com/sindresorhus/awesome) for truly join.
(Your Awesome badge is not linked to truly Awesome project URL)

**Comment by jaywcjlove** [comment]
I know Awesome macOS.
Awesome macOS are not active. 
Originally just want to do a Chinese list. The English list is the later thing.
So I went beyond the Awesome macOS star.

@havthgem

**Comment by jaywcjlove** [comment]
@havthgem  Also, the contents of the collection are different.

**Comment by havthgem** [comment]
Actually, I'm hope it can be included in the Awesome project. 😄

**Comment by jaywcjlove** [comment]
@havthgem Pull request [#1051](https://github.com/sindresorhus/awesome/issues/1051).  Wait for a merger.

**Comment by alichtman** [comment]
Migrated this to another issue. Closing for now.
