### ISSUE TITLE
How did you do the icons?

### ISSUE THREAD

**Issue by jacc** [jaywcjlove/awesome-mac#292]
I see that you did [OSS Icon]. How did you do that?

**Comment by jaywcjlove** [comment]
@jacc 

Find similar `svg` icons through icon search engine, Import into [Sketch](https://www.sketchapp.com) to adjust.

- https://www.iconfinder.com/
- http://iconfont.cn/
- http://www.easyicon.net/
- http://www.iconpng.com/
- http://findicons.com/
