### ISSUE TITLE
请问，有类似win下的绘图（mspaint）的轻量级软件吗？

### ISSUE THREAD

**Issue by willre** [jaywcjlove/awesome-mac#319]
一直想找一款类似win下的mspaint的轻量、简便的软件，但一直没遇到合适的，有合适的推荐吗？

**Comment by jaywcjlove** [comment]
@willre 轻量级，功能强大：http://www.pixelmator.com/mac/

**Comment by willre** [comment]
@jaywcjlove 这个我用过了，相比mspaint还是太重了，学习成本比mspaint高太多了。还不如“截图”里的画板好用，但“截图”里的画板有时候画图不方便，比如不支持画布大小调整什么的，还是mspaint方便。
“截图” 和 pixelmator 都不是我想要的

**Comment by jaywcjlove** [comment]
@willre 那你使用自带的预览工具就好了。

![image](https://user-images.githubusercontent.com/1680273/36838789-1841e976-1d7b-11e8-9188-c5160fc2620c.png)
