### ISSUE TITLE
建议修改 MacOS 为 macOS

### ISSUE THREAD

**Issue by xcv58** [jaywcjlove/awesome-mac#32]
根据官方网站的命名 http://www.apple.com/macos/sierra-preview/ 以及维基百科 https://en.wikipedia.org/wiki/OS_X

当单词 "Mac" 与 "OS" 同时出现时有两种情况：

1. 直接相连，这种都应该写为 macOS
2. 中间有空格，一般都写为 Mac OS

**Comment by jaywcjlove** [comment]
为了美观，我选择了第二个建议 `Mac OS`

**Comment by xcv58** [comment]
Thanks!
