### ISSUE TITLE
Free Software should be "no cost"

### ISSUE THREAD

**Issue by doctormo** [jaywcjlove/awesome-mac#320]
Since "Free Software" is the name of software liberation (i.e. software that gives you freedom) and not the name given to software that is free from cost (e.g. freeware) the tag should be changed from Free Software to "no cost" or similar distinctive phrase. (See google search for Free Software and links to fsf for reference)

(as a side note, the difference between Open Source and Free Software is wafer thin, but boils down to Open Sourceis about how development is done and Free Software is about how users are treated. Many projects are both, but I don't expect awesome-mac to make this distinction as it would be OTT)

**Comment by jaywcjlove** [comment]
@doctormo My English is very bad!  I need to study it.

Suggest not to distinguish between free and open source?

`Free Software` into `no cost`？

> "Free software" means software that respects users' freedom and community. Roughly, it means that the users have the freedom to run, copy, distribute, study, change and improve the software. Thus, "free software" is a matter of liberty To understand the concept, you should think of "free" as in "free speech," not as in "free beer". We sometimes call it "libre software," borrowing the French or Spanish word for "free" as in freedom, to show we do not mean the software is gratis.

Seems to be like this.

**Comment by doctormo** [comment]
@jaywcjlove My Chinese is even worse ;)

If you want, you can bundle Free Software and Open Source together to make FLOSS: 
![floss](https://user-images.githubusercontent.com/589384/36879432-c0cf5b76-1d91-11e8-9e8f-b0ae31145c4b.png)

But that is your choice, keep as Open Source is also ok.

For current `Free Software` that should become some new name, like `no cost` or `freeware` or similar. I like no cost because it's explicit.

**Comment by jaywcjlove** [comment]
`Free Software` => `freeware `

@doctormo I accept this suggestion.

**Comment by xcv58** [comment]
I think there is a difference between Freeware and Open Source. For example, some iOS App is open source but still sell on iOS App Store.

**Comment by jaywcjlove** [comment]
![Open-Source Software][OSS Icon] ![Freeware][Freeware Icon]

[OSS Icon]: https://jaywcjlove.github.io/sb/ico/min-oss.svg "Open Source Software"
[Freeware Icon]: https://jaywcjlove.github.io/sb/ico/min-free.svg "no cost"

```
![Open-Source Software][OSS Icon]
[OSS Icon]: https://jaywcjlove.github.io/sb/ico/min-oss.svg "Open Source Software"
```

@doctormo @xcv58 

There is no need to merge. Change the description?

```diff
 ![Freeware][Freeware Icon]
+ [Freeware Icon]: https://jaywcjlove.github.io/sb/ico/min-free.svg "Free Software"
- [Freeware Icon]: https://jaywcjlove.github.io/sb/ico/min-free.svg "freeware"
```

**Comment by doctormo** [comment]
@xcv58 - `Freeware` and `Open Source` are not related. `Free Software` is the big brother of `Open Source`. So `Free Software` is NOT related to `Freeware` they just have similar names.

Does this make the change make more sense?

@jaywcjlove - that change looks good to me.

**Comment by alichtman** [comment]
@jaywcjlove @doctormo Can we close this issue?
