### ISSUE TITLE
The code of conduct does not exist 

### ISSUE THREAD

**Issue by simon300000** [jaywcjlove/awesome-mac#359]
In [contributing.md](https://github.com/jaywcjlove/awesome-mac/blob/master/contributing.md), it suggest "*Please note that this project is released with a [Contributor Code of Conduct](https://github.com/jaywcjlove/awesome-mac/blob/master/code-of-conduct.md).*", But that does not exist in the repo.

**Comment by 1MSEZ** [comment]
still missing the file. needs to get fixed soon

**Comment by xcv58** [comment]
Fixed in 215aafbf158f7bf97b76f6716cbaa5d1c59babb6
