### ISSUE TITLE
跨平台抓包调试工具whistle

### ISSUE THREAD

**Issue by avwo** [jaywcjlove/awesome-mac#363]
[whistle](https://github.com/avwo/whistle)是基于Node实现的跨平台抓包调试工具： 

1. 完全跨平台，支持运行在Mac、Windows、Linux/Unix桌面及命令行系统
2. 支持抓包调试(改包)HTTP、HTTPS、WebSocket及Socket，可以修改请求响应的所有内容
3. 内置weinre，支持查看修改移动端网页的DOM结构
4. 内置Log功能，支持自动捕获网页的所有js异常及`console.xxx`输出各种类型数据
5. 操作简单，一切操作都可以通过类似配置hosts的方式实现
6. 支持通过Node模块的插件扩展功能

更多内容可以访问Github：[https://github.com/avwo/whistle](https://github.com/avwo/whistle)

**Comment by jaywcjlove** [comment]
@avwo 这是一个命令行的node包，并非 GUI 客户端
