### ISSUE TITLE
Proposal: add issue templates

### ISSUE THREAD

**Issue by xcv58** [jaywcjlove/awesome-mac#366]
GitHub has a new feature can add interactive template for issue creation:
![image](https://user-images.githubusercontent.com/503123/39606348-d96ad276-4ee9-11e8-83b4-5e5eef9998fe.png)

https://help.github.com/articles/about-issue-and-pull-request-templates/

Only the owner can click the Settings https://github.com/jaywcjlove/awesome-mac/settings to use interactive preview/edit feature to create templates.

![image](https://user-images.githubusercontent.com/503123/39606227-2c0c4074-4ee9-11e8-8111-a58888a89b4b.png)

I can put a PR if @jaywcjlove has no time.

For example:
https://github.com/xcv58/Tab-Manager-v2/tree/master/.github/ISSUE_TEMPLATE

**Comment by jaywcjlove** [comment]
@xcv58 @alichtman 
I have added a template. I don't know if this is correct or not.

**Comment by alichtman** [comment]
I added templates about a month ago, in the `docs` folder.

**Comment by jaywcjlove** [comment]
@alichtman 👌

**Comment by xcv58** [comment]
![image](https://user-images.githubusercontent.com/503123/39612527-167ee118-4f15-11e8-8d53-e608a16d0b6b.png)

It just works, thank you @jaywcjlove

**Comment by alichtman** [comment]
There should be an issue template for each of these:

1. New addition to list
2. Fixing bug in existing item in list
3. Removing item from list

I'll start adding them.
