### ISSUE TITLE
Please add FlyCut, Amazon Chime

### ISSUE THREAD

**Issue by Abhishek-dev2** [jaywcjlove/awesome-mac#373]
FlyCut - https://github.com/TermiT/Flycut
Amazon Chime - https://aws.amazon.com/chime/

**Comment by alichtman** [comment]
I don't think Amazon Chime belongs in this repo.
I think that CopyClip should be added to the repo (#97) instead off FlyCut. 

Closing this. @jaywcjlove reopen if you have a different opinion.
