### ISSUE TITLE
推荐增加 CommandQ

### ISSUE THREAD

**Issue by Cat7373** [jaywcjlove/awesome-mac#375]
我已经不知道多少次按`Command + A`或`Command + W`的时候不小心按成`Command + Q`导致应用直接退出了，这个小工具可以给`Command + Q`加一个延时，要按够一小段时间才能关闭应用，个人感觉非常实用😂

[也不知道是不是官网，反正我是从这里下的😂](https://clickontyler.com/commandq/)

**Comment by jaywcjlove** [comment]
@Cat7373 感觉这个是一个鸡肋软件，开着它，消耗电脑资源。

**Comment by Cat7373** [comment]
消耗不太多😂
我是刚好有这个需求，不知道其他有这种需求的人多不多 😂

**Comment by xcv58** [comment]
我也觉得没有必要。

**Comment by CarlosEvo** [comment]
感觉用khd能写一个脚本出来？？？

**Comment by Vergegung** [comment]
@Cat7373 我觉得还挺趣的，感谢分享。谢谢

**Comment by alichtman** [comment]
This could definitely be useful to have on the list. I support adding it.

**Comment by leomikezee** [comment]
这个有个[开源替代品](https://github.com/dteoh/SlowQuitApps)

**Comment by alichtman** [comment]
The `Open Source` option is better than the `closed source` one. 

@leomikezee open a PR with that and I'll approve it.

**Comment by leomikezee** [comment]
Made a PR #400 @alichtman

**Comment by alichtman** [comment]
Merged. Thanks!
