### ISSUE TITLE
It's unclear how 'hot' icon works

### ISSUE THREAD

**Issue by heldev** [jaywcjlove/awesome-mac#386]
Would be great to know the rules how 'Hot' badge is assigned otherwise, It doesn't help a viewer to choose an app or a submitter to submit a PR with that badge.

**Comment by xcv58** [comment]
I think it was personal opinion. But the criterion is not clear. Maybe @jaywcjlove can clarify.

**Comment by jaywcjlove** [comment]
There was no standard before. Previously judged by using experience.

@xcv58 @alchtman  Need to define a standard?

**Comment by alichtman** [comment]
Closing this, migrated discussion to another issue.
