### ISSUE TITLE
Remove Chinese-specific items from English README

### ISSUE THREAD

**Issue by alichtman** [jaywcjlove/awesome-mac#392]
**Put "Remove ____" as Title**
 [x] Done

**Why it should be removed**

They do belong on the Chinese list, but it makes no sense to put the Chinese-specific apps on the english README, imo.

Everything that's noted with: **Missing English UI and Docs** should be removed from `README.md`.

**Comment by alichtman** [comment]
That's part of the issue template. It means that multiple requests shouldn't be put into the same PR. For example, adding two distinct programs to the list should be two separate issues/PRs. It doesn't apply in the way you interpreted for this issue because this is a reorganization thing.

**Comment by jaywcjlove** [comment]
If it is not used, it can be Remove Chinese-specific items from English README.
