### ISSUE TITLE
Add nvALT

### ISSUE THREAD

**Issue by leomikezee** [jaywcjlove/awesome-mac#396]
NOTE: Each discrete (stand-alone) request should be in its own issue.

**Put "Add ____" as Title**
 [x] Done

**Provide a link to the proposed addition.**
http://brettterpstra.com/projects/nvalt/

**Explain why it should be added**
A convenient tool for taking note.

**Additional context**

> Notational Velocity is a way to take notes quickly and effortlessly using just your keyboard.

### Issue Checklist

Put an x in the boxes once you've completed each step. You can also fill these out after creating the issue. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before responding to the issue.

- [x] I have checked for other similar issues
- [x] I have explained why this change is important
- [x] I have added necessary documentation (if appropriate)

**Comment by alichtman** [comment]
I think we've covered text editors and note-taking pretty completely. I'm gonna err on the side of not adding this.
