### ISSUE TITLE
Add smcFanControl

### ISSUE THREAD

**Issue by leomikezee** [jaywcjlove/awesome-mac#397]
NOTE: Each discrete (stand-alone) request should be in its own issue.

**Put "Add ____" as Title**
 [x] Done

**Provide a link to the proposed addition.**
https://github.com/hholtmann/smcFanControl

**Explain why it should be added**
A small tool can that can set the fan speed manually.

**Additional context**
Can be used to cool down the mac.

### Issue Checklist

Put an x in the boxes once you've completed each step. You can also fill these out after creating the issue. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before responding to the issue.

- [x] I have checked for other similar issues
- [x] I have explained why this change is important
- [x] I have added necessary documentation (if appropriate)

**Comment by alichtman** [comment]
Open a PR

**Comment by leomikezee** [comment]
Made PR #403

**Comment by xcv58** [comment]
It seems not actively maintained. The latest release is Oct 2016: https://github.com/hholtmann/smcFanControl/releases

**Comment by alichtman** [comment]
Thanks for checking, @xcv58.

I agree this should not be added, as it's no longer maintained.

My bad on that call.
