### ISSUE TITLE
Add f.lux

### ISSUE THREAD

**Issue by roman-1983** [jaywcjlove/awesome-mac#399]
NOTE: Each discrete (stand-alone) request should be in its own issue.

**Put "Add ____" as Title**
 [x] Done

**Provide a link to the proposed addition.**
https://justgetflux.com/

**Explain why it should be added**
f.lux makes the color of the computer's display adapt to the time of day, warm at night and like sunlight during the day - like the "night mode" on android/iOS and High Sierra (but with a better logic).

**Additional context**
![f.lux screenshot](https://justgetflux.com/images/flux-windows.jpg)

### Issue Checklist
- [x] I have checked for other similar issues
- [x] I have explained why this change is important
- [x] I have added necessary documentation (if appropriate)

**Comment by alichtman** [comment]
Open a PR.

**Comment by roman-1983** [comment]
It's already added.
