### ISSUE TITLE
一个方便看 awesome-mac 的文档的小站

### ISSUE THREAD

**Issue by ripperhe** [jaywcjlove/awesome-mac#411]
我发现看网站 [https://git.io/macx](https://git.io/macx) 的时候有些不太方便，然后利用 [docsify](https://github.com/docsifyjs/docsify) 生成了一个小网站，直接引用的 `README-zh.md` 文件，所以会根据 `awesome-mac` 仓库文件自动更新~

```html
<script>
    window.$docsify = {
      homepage:
      'https://raw.githubusercontent.com/jaywcjlove/awesome-mac/master/README-zh.md',
    }
  </script>
```

`链接 👉` [https://ripperhe.com/awesome-mac-html](https://ripperhe.com/awesome-mac-html)
`仓库地址 👉` [https://github.com/ripperhe/awesome-mac-html](https://github.com/ripperhe/awesome-mac-html)

**Comment by jaywcjlove** [comment]
**Awesome Mac App for macOS**. Installers for the latest stable build for Mac can be [downloaded here](https://github.com/jaywcjlove/amac/releases).

[![Get it on macOS](http://jaywcjlove.github.io/sb/download/macos.svg)](https://github.com/jaywcjlove/amac/releases)
