### ISSUE TITLE
Decluttering: leverage existing awesome lists

### ISSUE THREAD

**Issue by heldev** [jaywcjlove/awesome-mac#431]
**Is your feature request related to a problem? Please describe.**
There are few "sublists" in this list (sublime plugins, WebStorm plugins, maybe even docker tools ...) for all them there are dedicated awesome lists, which provide more comprehensive and updated information. Would be nice to leverage this opportunity to declutter this list and at the same time provide better info. 

**Describe the solution you'd like**
Perhaps we can add a new icon with a link to a corresponding list.
And merge information from this project to other awesome lists (if it's needed).

**Describe alternatives you've considered**
I'm not sure what about the docker part. On the one hand, it's nice to have all mac apps here, but on the other, the list is already big, we can't keep up with their ecosystem (awesome docker have more UIs that this list does) and the option of having web-apps (like "true" web apps, not electron based) seems questionable to me so I think it's better to remove all docker related stuff and put a link in front of the docker item to the docker awesome list.

**Additional context**

### Issue Checklist

Put an x in the boxes once you've completed each step. You can also fill these out after creating the issue. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before responding to the issue.

- [x] I have checked for other similar issues
- [x] I have explained why this change is important
- [x] I have added necessary documentation (if appropriate)

**Comment by alichtman** [comment]
I'm a fan of this proposal.

**Comment by jaywcjlove** [comment]
@heldev This proposal is great and support.
