### ISSUE TITLE
「Mac OS X Manual Pages - 官方Mac命令操作手册。Freeware」链接失效

### ISSUE THREAD

**Issue by dofy** [jaywcjlove/awesome-mac#434]
命令行工具下面的 `「Mac OS X Manual Pages - 官方Mac命令操作手册。Freeware」` 链接失效

**Comment by alichtman** [comment]
It's documentation on the http://developer.apple.com/ website, not really a tool.

It's like opening a terminal and typing `$ man COMMAND`.

I don't think this is a valid addition, tbh
