### ISSUE TITLE
Add fisherman

### ISSUE THREAD

**Issue by inductor** [jaywcjlove/awesome-mac#437]
NOTE: Each discrete (stand-alone) request should be in its own issue.

**Put "Add ____" as Title**
[x] Done

**Provide a link to the proposed addition.**
https://github.com/fisherman/fisherman

**Explain why it should be added**
Fish is on the list and so is bash-it and Oh my zsh. So why not? ;)

**Additional context**
None

### Issue Checklist

Put an x in the boxes once you've completed each step. You can also fill these out after creating the issue. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before responding to the issue.

- [x] I have checked for other similar issues
- [x] I have explained why this change is important
- [x] I have added necessary documentation (if appropriate)

**Comment by heldev** [comment]
It was deleted in #431 because fish has a dedicated awesome list and fisherman is there

**Comment by inductor** [comment]
Airght thanks
