### ISSUE TITLE
Add Setapp

### ISSUE THREAD

**Issue by S1ngS1ng** [jaywcjlove/awesome-mac#461]
- Setapp - The best apps for Mac in one suite: https://setapp.com

Subscribed to it since they were on beta, now I've made the subscription to the annual plan. Setapp is a subscription service of Mac apps.

This service is provided by MacPaw, which is famous for Clean My Mac (as well as Clean My PC) and Gemini. It might worth to mention that they acquired The Unarchiver.

Some noticeable apps that I use continuously are:
- Clean My Mac X
- iStat Menus
- 2Do
- Paste
- Marked
- Ulysses
- Bartender
- Archiver
- Numi
- IconJar
- Image2icon
- Sip
- Boom 3D
- HazeOver
- Folx
- Noizio

And yes, there are more apps available: https://setapp.com/apps 
All apps are full version, no more in-app purchase.

### Issue Checklist

- [ x ] I have checked for other similar issues
- [ x ] I have explained why this change is important
- [ x ] I have added necessary documentation (if appropriate)

**Comment by xcv58** [comment]
I'm surprised Setapp is not on the list yet.
