### ISSUE TITLE
[Question] Suspicious email

### ISSUE THREAD

**Issue by S1ngS1ng** [jaywcjlove/awesome-mac#467]
Got this email few days ago:
![image](https://user-images.githubusercontent.com/13592559/46425936-e703bd00-c6f1-11e8-8f21-926ba0fc717d.png)

, where our friend/fiend is: https://github.com/ipusi

@jaywcjlove AFAIC, I have no clue how you guys are related.
cc @xcv58

**Comment by xcv58** [comment]
I got the same one, I thought it's just phishing.
