### ISSUE TITLE
Add Lulu

### ISSUE THREAD

**Issue by beardcoder** [jaywcjlove/awesome-mac#480]
NOTE: Each discrete (stand-alone) request should be in its own issue.

**Put "Add ___" as Title**
- [x] Done

**Provide a link to the proposed addition.**
https://objective-see.com/products/lulu.html

**Explain why it should be added**
Open source alternative to litle snitch

**Additional context**
Firewall and network traffic monitoring

### Issue Checklist

Put an x in the boxes once you've completed each step. You can also fill these out after creating the issue. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before responding to the issue.

- [x] I have checked for other similar issues
- [x] I have explained why this change is important
- [x] I have added necessary documentation (if appropriate)

**Comment by alichtman** [comment]
Open a PR and I'll merge it in.

**Comment by beardcoder** [comment]
Well done
