### ISSUE TITLE
Add MakeHuman

### ISSUE THREAD

**Issue by MCISTL** [jaywcjlove/awesome-mac#492]
NOTE: Each discrete (stand-alone) request should be in its own issue.

**Put "Add ____" as Title**
 [x] Done

**Provide a link to the proposed addition.**
http://www.makehumancommunity.org/

**Explain why it should be added**
Powerful and FREE 3D human modeler. Similar to an early version of Poser.

**Additional context**

### Issue Checklist

Put an x in the boxes once you've completed each step. You can also fill these out after creating the issue. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before responding to the issue.

- [x] I have checked for other similar issues
- [x] I have explained why this change is important
- [x] I have added necessary documentation (if appropriate)

**Comment by jaywcjlove** [comment]
@MCISTL The macOS platform downloader was not found.

**Comment by jaywcjlove** [comment]
Found it:
![image](https://user-images.githubusercontent.com/1680273/51720004-abb54180-2086-11e9-8893-31707722aebe.png)

@MCISTL You can open a PR and I will merge it.
