### ISSUE TITLE
Add ssh-am

### ISSUE THREAD

**Issue by gengxiankun** [jaywcjlove/awesome-mac#503]
NOTE: Each discrete (stand-alone) request should be in its own issue.

Put "Add ____" as Title
[x] Done

**Provide a link to the proposed addition.**
https://github.com/gengxiankun/ssh-am

**Explain why it should be added**
ssh-am 是一款 macOS Command Line Tools，用于管理服务器的账户信息，内置ssh和scp命令。并支持多种登陆方式的自动化授权（包括google二次认证的授权方式）。

**Additional context**
![image](https://user-images.githubusercontent.com/19488539/49338364-05872580-f65b-11e8-9541-d15db33827f7.png)

### Issue Checklist
- [x] I have checked for other similar issues
- [x] I have explained why this change is important
- [x] I have added necessary documentation (if appropriate)

**Comment by jaywcjlove** [comment]
@gengxiankun 你这个可能提交错地方了？[awesome-macos-command-line](https://github.com/herrbischoff/awesome-macos-command-line)

**Comment by gengxiankun** [comment]
i know, thk u.

**Comment by gengxiankun** [comment]
> @gengxiankun 你这个可能提交错地方了？[awesome-macos-command-line](https://github.com/herrbischoff/awesome-macos-command-line)

I know, thk u.

**Comment by alichtman** [comment]
This functionality is covered by the `~/.ssh/config` file. This project is entirely redundant imo.
