### ISSUE TITLE
Add eZip

### ISSUE THREAD

**Issue by vitacoding** [jaywcjlove/awesome-mac#509]
NOTE: Each discrete (stand-alone) request should be in its own issue.

**Put "Add ____" as Title**
 [x] Done

**Provide a link to the proposed addition.**
http://ezip.awehunt.com

**Explain why it should be added**
eZip is an archiver for macOS with tersely but complete functions. It supports popular formats and works great with Mojave dark-mode, QuickLook and Drag decompression.

eZip 是一款界面简洁，功能完善，支持主流的多种压缩格式的解压软件。完美适配 Mojave 深色模式、QuickLook 和拖拽解压。

**Additional context**
[Web Site](http://ezip.awehunt.com)

### Issue Checklist

Put an x in the boxes once you've completed each step. You can also fill these out after creating the issue. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before responding to the issue.

- [x] I have checked for other similar issues
- [x] I have explained why this change is important
- [x] I have added necessary documentation (if appropriate)

**Comment by jaywcjlove** [comment]
@vitacoding  Push RP ?
