### ISSUE TITLE
正版软件购买渠道添加建议

### ISSUE THREAD

**Issue by wangyadong97** [jaywcjlove/awesome-mac#512]
NOTE: Each discrete (stand-alone) request should be in its own issue.

**Is your feature request related to a problem? Please describe.**
As one of the few genuine software agents in China, DIGITALYCHEE has always been committed to  people enjoy more favorable genuine software.

**Describe the solution you'd like**
Can you consider adding DIGITALYCHEE to the genuine/introduction entry?

**Describe alternatives you've considered**

**Additional context**
DIGITALYCHEE official website： https://www.lizhi.io
DIGITALYCHEE store:  https://www.lizhi.io/store

### Issue Checklist

Put an x in the boxes once you've completed each step. You can also fill these out after creating the issue. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before responding to the issue.

- [ ] I have checked for other similar issues
- [ ] I have explained why this change is important
- [ ] I have added necessary documentation (if appropriate)

**Comment by xcv58** [comment]
我觉得可以在中文版里单独添加一个条目， @jaywcjlove 你觉得呢？

**Comment by jaywcjlove** [comment]
![image](https://user-images.githubusercontent.com/1680273/50532372-5fdcae80-0b53-11e9-908a-7d00a3447777.png)
![image](https://user-images.githubusercontent.com/1680273/50532377-666b2600-0b53-11e9-8443-2c8dd910dc33.png)

@xcv58  有的， 如果在软件后面添加正版购买渠道，非官方的，我希望 **`有偿打广告`**。

比如，前面有个软件厂商联系我，希望他的软件加粗高亮，并且在显眼的位置，我希望他赠送五套正版的软件给我们这里的贡献者，最终没有达成这个愿望。

@wangyadong97 如果你有类似的要求：

> 你可以发个 issue 告知大家免费送几套软件  
> 然后告诉大家规则送软件的规则  

我将 **「数码荔枝」** 放到中文版的最顶部
