### ISSUE TITLE
Add Boostnote

### ISSUE THREAD

**Issue by lutfiyanra** [jaywcjlove/awesome-mac#519]
NOTE: Each discrete (stand-alone) request should be in its own issue.

**Put "Add ____" as Title**
 [x] Done

**Provide a link to the proposed addition.**
official web : https://boostnote.io/
github repo : https://github.com/BoostIO/Boostnote/

**Explain why it should be added**
Open Source, Intuitive UI, easy to customize and can works on any devices

**Additional context**
<img width="1440" alt="screen shot 2019-01-11 at 14 51 40" src="https://user-images.githubusercontent.com/32807788/51020304-bebd1180-15b0-11e9-8f90-86e3548fdda3.png">

for more screenshot you can visit their official site above.

### Issue Checklist

Put an x in the boxes once you've completed each step. You can also fill these out after creating the issue. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before responding to the issue.

- [v] I have checked for other similar issues
- [v] I have explained why this change is important
- [v] I have added necessary documentation (if appropriate)

**Comment by jaywcjlove** [comment]
@lutfiyanra Push `PR`?
