### ISSUE TITLE
Add Highland 2; Delete 云梯

### ISSUE THREAD

**Issue by hmumixaM** [jaywcjlove/awesome-mac#522]
1. Highland 2
Official website: https://quoteunquoteapps.com/highland-2/
MAS: https://itunes.apple.com/cn/app/highland-2/id1171820258
Description: 一个拥有大纲管理和写作资料管理面板的 Markdown 编辑器。

2. 云梯已在一年前十月跑路，最新官网虽能打开，但是所有服务器已停止链接。

3. 推荐 ssglobal，有无限试用高速 Shadowsocks 服务器，能够支持 Netflix、Dmm 等视频播放网站。
官网：http://ssglobal.co
P.S.: 官网登录需要 VPN 支持，且不支持在线购买，需要试用 Telegram 联系店主购买。

**Comment by jaywcjlove** [comment]
@hmumixaM ssglobal 账号注册了都无法登录，也没有免费ssr账号。

Highland 2 可以提交一个 ` Pull requests`
