### ISSUE TITLE
给同类型的应用-加上推荐指数评分

### ISSUE THREAD

**Issue by bluemsn** [jaywcjlove/awesome-mac#525]
列了非常多的应用，同类型的组件，都有N多种，建议可以 反馈出来一些【推荐指数】评分、或者下载关注数量的信息，给到用户~

比如：

* VS Code 【*****】
* atom 【***】
* subline Text 【****】

**Comment by jaywcjlove** [comment]
@bluemsn 之前加了，后面删除了，具体什么原因删除，你可以找一下issue，忘记了

![image](https://user-images.githubusercontent.com/1680273/51094983-3dea5980-17ec-11e9-82d3-cb03b070f014.png)

**Comment by jaywcjlove** [comment]
@bluemsn 

https://github.com/jaywcjlove/awesome-mac/tree/a6ab675d56f679f37a8b08626f87cedc3a145eff
