### ISSUE TITLE
Remove duplicate mention of JetBrains GoLand

### ISSUE THREAD

**Issue by nickdaria** [jaywcjlove/awesome-mac#532]
NOTE: Each discrete (stand-alone) request should be in its own issue.

**Put "Remove ____" as Title**
 [X ] Done

**Explain why it should be removed**
There are two mentions of GoLand, and removing the second would leave the entry under JetBrains Toolbox.

**Additional context**
Corrected version available [here](https://gist.github.com/nickdaria/d16e3b48f652c1f9573c0b6c02931dcc) for context.

**Comment by jaywcjlove** [comment]
@nickdaria thx!

**Comment by nickdaria** [comment]
No problem! Great list.
