### ISSUE TITLE
Add Colorpicker

### ISSUE THREAD

**Issue by Toinane** [jaywcjlove/awesome-mac#534]
NOTE: Each discrete (stand-alone) request should be in its own issue.

**Put "Add ____" as Title**
 [x] Done

**Provide a link to the proposed addition.**
https://colorpicker.crea-th.at

**Explain why it should be added**
This application allow me to get any colors on screen, get similar colors and saves it in categories.

**Additional context**
It's a free and open-sourced application available here: https://github.com/Toinane/colorpicker

### Issue Checklist

Put an x in the boxes once you've completed each step. You can also fill these out after creating the issue. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before responding to the issue.

- [x] I have checked for other similar issues
- [x] I have explained why this change is important
- [x] I have added necessary documentation (if appropriate)

**Comment by jaywcjlove** [comment]
@Toinane Open a PR and I'll merge it in.

**Comment by Toinane** [comment]
Thank you 👍
