### ISSUE TITLE
提供某几种常见搭配。给了太多选择项反而不知道怎么选择了

### ISSUE THREAD

**Issue by shuihuakeji** [jaywcjlove/awesome-mac#538]
NOTE: Each discrete (stand-alone) request should be in its own issue.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### Issue Checklist

Put an x in the boxes once you've completed each step. You can also fill these out after creating the issue. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before responding to the issue.

- [ ] I have checked for other similar issues
- [ ] I have explained why this change is important
- [ ] I have added necessary documentation (if appropriate)

**Comment by jaywcjlove** [comment]
去看 #525
