### ISSUE TITLE
Add Windscribe

### ISSUE THREAD

**Issue by co16353sidak** [jaywcjlove/awesome-mac#542]
NOTE: Each discrete (stand-alone) request should be in its own issue.

**Put "Add ____" as Title**
 - [x] Done

**Provide a link to the proposed addition.**
https://windscribe.com

**Explain why it should be added**
Quick, Very easy to start from the menu bar, gives 10gn per month free on the spot and speeds are very good, shows virtual ip and location forwarding and gives limited(on free) location control. Whereas the pro version is just OP.

**Additional context**
<img width="356" alt="screenshot 2019-01-25 at 1 07 58 am" src="https://user-images.githubusercontent.com/35738138/51703915-aa135b80-203d-11e9-9e05-ef95a2d70c75.png">
<img width="354" alt="screenshot 2019-01-25 at 1 09 12 am" src="https://user-images.githubusercontent.com/35738138/51703970-d7f8a000-203d-11e9-8e1e-6c1a1a405eeb.png">

### Issue Checklist

Put an x in the boxes once you've completed each step. You can also fill these out after creating the issue. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before responding to the issue.

- [x] I have checked for other similar issues
- [x] I have explained why this change is important
- [x] I have added necessary documentation (if appropriate)

**Comment by jaywcjlove** [comment]
@co16353sidak Open a PR and I'll merge it in.
