### ISSUE TITLE
建议加一个投票

### ISSUE THREAD

**Issue by lovexi** [jaywcjlove/awesome-mac#55]
只是一个小建议，如果可以的话，我觉得有一个投票就最好啦，这样可以很直观的看出来哪些是热门。

**Comment by jaywcjlove** [comment]
怎么投票，那么多应用投票哪些软件呢？

**Comment by lovexi** [comment]
repo主可以分类投票，每个类选几个典型的吧，如果有人想投一个软件但没有列在上面，可以自己往上添加选项。我觉得surveyMonkey什么的应该支持这个功能。

**Comment by jaywcjlove** [comment]
@lovexi 已经加了，在`issue` 里面做 投票的事儿  用 👍  和 👎 来做投票功能，推荐软件可以打个`tag`，例如： #57  这样做，当一些软件有争议需要投票的，放在这里投票一阵子，然后我会选择，是否收录
