### ISSUE TITLE
Add jet-live

### ISSUE THREAD

**Issue by ddovod** [jaywcjlove/awesome-mac#553]
NOTE: Each discrete (stand-alone) request should be in its own issue.

**Put "Add ____" as Title**
 [x] Done

**Provide a link to the proposed addition.**
https://github.com/ddovod/jet-live

**Explain why it should be added**
The library allows to reload c++ (and probably obj-c, I didn't test it) code on the fly without app restart.

**Additional context**
Here's a [demo](https://www.youtube.com/watch?v=5xfgViYchqg) video, was created under linux, but the library provides same experience on mac.

### Issue Checklist

Put an x in the boxes once you've completed each step. You can also fill these out after creating the issue. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before responding to the issue.

- [x] I have checked for other similar issues
- [x] I have explained why this change is important
- [x] I have added necessary documentation (if appropriate)

**Comment by jaywcjlove** [comment]
@ddovod This may not be suitable for this list.

**Comment by ddovod** [comment]
Okay, no problem
