### ISSUE TITLE
Add Streaker

### ISSUE THREAD

**Issue by jamieweavis** [jaywcjlove/awesome-mac#556]
NOTE: Each discrete (stand-alone) request should be in its own issue.

**Put "Add ____" as Title**
- [x] Done

**Provide a link to the proposed addition.**
https://github.com/jamieweavis/streaker

**Explain why it should be added**
GitHub contribution streak tracking menubar app.

**Additional context**

Open source & free.

*Screenshots:*

![image](https://user-images.githubusercontent.com/8133259/52555071-99563a00-2de0-11e9-8e3e-2ae52bcd3869.png)

![image](https://user-images.githubusercontent.com/8133259/52555085-9eb38480-2de0-11e9-907e-4b494d4a10b7.png)

### Issue Checklist

Put an x in the boxes once you've completed each step. You can also fill these out after creating the issue. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before responding to the issue.

- [x] I have checked for other similar issues
- [x] I have explained why this change is important
- [x] I have added necessary documentation (if appropriate)

**Comment by jaywcjlove** [comment]
@jamieweavis You can open a PR and I will merge it.
