### ISSUE TITLE
Add Flume

### ISSUE THREAD

**Issue by shenwusw** [jaywcjlove/awesome-mac#560]
NOTE: Each discrete (stand-alone) request should be in its own issue.

**Put "Add ____" as Title**

[x] Done

**Provide a link to the proposed addition.**
https://flumeapp.com

**Explain why it should be added**
A beautiful Instagram experience for your Mac.

**Additional context**
The free version is good enough if you only want to do the browsing instead of posting. 
Excellent UI.
<img width="327" alt="screen shot 2019-02-16 at 2 13 22 pm" src="https://user-images.githubusercontent.com/13981903/52895418-158fb980-31f5-11e9-82a9-16f5018bb254.png">

### Issue Checklist

Put an x in the boxes once you've completed each step. You can also fill these out after creating the issue. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before responding to the issue.

- [x] I have checked for other similar issues
- [x] I have explained why this change is important
- [x] I have added necessary documentation (if appropriate)

**Comment by jaywcjlove** [comment]
@shenwusw You can open a PR and I will merge it.

**Comment by shenwusw** [comment]
@jaywcjlove how about the category? "Collaboration and Team Tools" seems a bit weird.

**Comment by jaywcjlove** [comment]
@shelltea This is a "Social Networking" category, but we don't.

**Comment by tiptronic85** [comment]
I think you can close this ticket, flumeapp.com domain is for sale
