### ISSUE TITLE
How did you create icons?

### ISSUE THREAD

**Issue by zxdawn** [jaywcjlove/awesome-mac#565]
How did you create these small icons? They look so beautiful!

I want to create my own icons for my repository. Is it possible?
![image](https://user-images.githubusercontent.com/30388627/52944121-aa3b1880-33a9-11e9-9d3b-edff85d1975a.png)

**Comment by jaywcjlove** [comment]
@zxdawn Of course you can. I created these icons using Sketch, which is very simple to use.

These small icon source files are stored here: https://github.com/jaywcjlove/sb  
The Sketch source file is here: https://github.com/jaywcjlove/sb/tree/gh-pages/svg

**Comment by zxdawn** [comment]
@jaywcjlove Why some small icons can be used in README.md by `** icon` and some not?
```
![Open-Source Software][OSS Icon] means **open source**, click to open **open source** repo;\
![Freeware][Freeware Icon] means **free** to use, or **free** personal license;\
![App Store][app-store Icon] means **App store** hyperlink;\
![Awesome List][awesome-list Icon] means hyperlink to a corresponding **Awesome list** for the item;
```

**Comment by jaywcjlove** [comment]
@zxdawn This is the `markdown` syntax. Two ways to insert a picture：

![](https://jaywcjlove.github.io/sb/lang/english.svg)

```markdown
![](https://jaywcjlove.github.io/sb/lang/english.svg)
```


![Open-Source Software][OSS Icon]


```markdown
![Open-Source Software][OSS Icon]

[OSS Icon]: https://jaywcjlove.github.io/sb/ico/min-oss.svg
```


[OSS Icon]: https://jaywcjlove.github.io/sb/ico/min-oss.svg

**Comment by zxdawn** [comment]
@jaywcjlove Thank you! Never used that before :+1:
