### ISSUE TITLE
RTX腾讯通 企业内部的聊天软件

### ISSUE THREAD

**Issue by aliliin** [jaywcjlove/awesome-mac#568]
NOTE: Each discrete (stand-alone) request should be in its own issue.

**Put "Add ___" as Title**
RTX_腾讯通企业内部聊天软件

**Provide a link to the proposed addition.**
https://www.rtxapp.com/mac/

**Explain why it should be added**
还是有一部分企业内部在使用此通讯工具的，这个软件有Mac版本也是win版本，连接是Mac版本的。

**Additional context**
![image](https://user-images.githubusercontent.com/22074839/53161616-4745bd80-3605-11e9-9416-0c6dc071161b.png)

### Issue Checklist

Put an x in the boxes once you've completed each step. You can also fill these out after creating the issue. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before responding to the issue.

- [ ] I have checked for other similar issues
- [ ] I have explained why this change is important
- [ ] I have added necessary documentation (if appropriate)

**Comment by jaywcjlove** [comment]
@aliliin 欢迎提一个 PR，我会将它合并。谢谢！

**Comment by aliliin** [comment]
@jaywcjlove 已经提交。
