### ISSUE TITLE
推荐 Manico 

### ISSUE THREAD

**Issue by liyatang** [jaywcjlove/awesome-mac#57]
Manico 是一个为 OS X 设计的快速的 App 启动和切换工具

**Comment by jaywcjlove** [comment]
@liyatang 启动和切换是干什么的呢？不适系统自带软件切换的吗？

**Comment by xcv58** [comment]
@jaywcjlove Manico 是一个 [TualatriX](https://imtx.me/) 开发的 App 切换工具，我觉得主要的好处是可以自己定义不同 App 的切换快捷键。但我并没有作为主力使用，因为不能用文件来管理配置。

**Comment by jaywcjlove** [comment]
这个要加上吗？感觉没有什么卵用哦，系统好像也可以

**Comment by yPangXie** [comment]
用过一阵子, 不是重度用户.

**Comment by liyatang** [comment]
@jaywcjlove 就是快速启动和切换App的工具，一个特别小的工具，“简单. 容易. 快速”。系统自带的也可以，但Manico更好用吧，个人看法。
起码我每刻都在使用，还宁愿为它付费了。

**Comment by S1ngS1ng** [comment]
挺好的工具。不过这个完全可以通过 HammerSpoon 的配置文件实现。

**Comment by xcv58** [comment]
同意楼上的观点，同样的功能 HammerSpoon，Alfred 都可以很容易的实现。而且这是个面向开发者和设计师的软件列表

**Comment by liyatang** [comment]
@xcv58 没了解过HammerSpoon，我说下Alfred吧。   其实Manico也没啥功能，很多软件都可以达到。 但Alfred你要调他出来，输入你想切换的app，按了多少键？  Manico无非就是一个快捷键，一按马上就切换，仅此而已。当然你想自己写个快捷键程序出来都行呢。

在app间频繁切换有Manico就很方便了。

**Comment by liyatang** [comment]
@xcv58 @S1ngS1ng 刚看了下 HammerSpoon ，确实不错。 支持 HammerSpoon。

**Comment by xcv58** [comment]
@liyatang 不好意思，没表达清楚。我说 Alfred 能实现同样功能是指用 Workflow 来实现，自定义快捷键 切换/启动 特定的 App。而不是打开 Alfred 的窗口来实现切换。

**Comment by liyatang** [comment]
@xcv58 学习了 ☺️

**Comment by xcv58** [comment]
@liyatang 互相学习啊 :)
