### ISSUE TITLE
Adding testing tool which it had been used in many company

### ISSUE THREAD

**Issue by shijiezhou1** [jaywcjlove/awesome-mac#571]
NOTE: Each discrete (stand-alone) request should be in its own issue.

**Put "Add Katalon Studio " as Title**
 [x] Done

**Provide a link to the proposed addition.**
[https://www.katalon.com/](https://www.katalon.com/)

**Explain why it should be added**

The test automation framework provided within Katalon Studio was developed with the keyword-driven approach as the primary test authoring method with data-driven functionality for test execution. The user interface is a complete integrated development environment (IDE) implemented on Eclipse rich client platform (RCP). The keyword libraries are a composition of common actions for web, API, and mobile testings. External libraries written in Java can be imported into a project to be used as native functions. The main scripting language is Groovy, Java, and JavaScript and can be executed against all modern browsers, iOS, and Android applications supported by Selenium and Appium.

**Additional context**

https://en.wikipedia.org/wiki/Katalon_Studio

### Issue Checklist

Put an x in the boxes once you've completed each step. You can also fill these out after creating the issue. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before responding to the issue.

- [x] I have checked for other similar issues
- [x] I have explained why this change is important
- [x] I have added necessary documentation (if appropriate)

**Comment by jaywcjlove** [comment]
@shijiezhou1 You can open a PR and I will merge it.

**Comment by shijiezhou1** [comment]
Thank you so much. I had created the pull request. Can you review it?

Add new advanced testing tools Katalon Studio because it is popular in
United State #593 <https://github.com/jaywcjlove/awesome-mac/pull/593>

Thank you again!

**Comment by jaywcjlove** [comment]
@shijiezhou1 I merge it.

**Comment by shijiezhou1** [comment]
Thank you so much you are the best
