### ISSUE TITLE
New File Menu

### ISSUE THREAD

**Issue by dingzihu** [jaywcjlove/awesome-mac#585]
New File Menu   
Mac系统中创建文件/文档的最佳利器，安装软件后你可以直接在Finder文件夹中点击鼠标右键菜单新建文档。
通过用户自定义模板的方式，New File Menu可以支持创建几乎所有格式的文件。

**Comment by Koma-Andrea** [comment]
English please?!

**Comment by someonewithsomepower** [comment]
> English please?!

It means you can create new files quickly.
You can download the software from appstore.

**Comment by jaywcjlove** [comment]
@dingzihu 没有连接地址？AppStore 有好多款。
