### ISSUE TITLE
推荐 MacHider

### ISSUE THREAD

**Issue by xuelangZF** [jaywcjlove/awesome-mac#59]
是不是有一些文件、图片不想被别人看到？作为程序员，你当然可以通过设置权限阻止别人来看。不过我们有更简单的方法，那就是用MacHider来隐藏文件了。

https://github.com/xuelangZF/MacOSX/blob/gh-pages/apps/macHider.md

**Comment by jaywcjlove** [comment]
希望推荐免费好用的软件，收费的只收录流行的
