### ISSUE TITLE
Add SuperDuper!

### ISSUE THREAD

**Issue by margoussian** [jaywcjlove/awesome-mac#592]
NOTE: Each discrete (stand-alone) request should be in its own issue.

**Put "Add ____" as Title**
 [x ] Done

**Provide a link to the proposed addition.**
https://shirt-pocket.com/SuperDuper/SuperDuperDescription.html

**Explain why it should be added**
Painless fully bootable disk backups.

### Issue Checklist

Put an x in the boxes once you've completed each step. You can also fill these out after creating the issue. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before responding to the issue.

- [x ] I have checked for other similar issues
- [x ] I have explained why this change is important
- [x ] I have added necessary documentation (if appropriate)

**Comment by jaywcjlove** [comment]
@margoussian You can open a PR and I will merge it.

**Comment by margoussian** [comment]
Thanks. Created PR: https://github.com/jaywcjlove/awesome-mac/pull/594
