### ISSUE TITLE
Marp links to outdated version

### ISSUE THREAD

**Issue by chriszo111** [jaywcjlove/awesome-mac#596]
**Provide a link to the proposed addition.**
Even though the old [Marp]() link still works, the creator decided a while ago that they would discontinue the linked version and continue with a new repo, reachable @ https://marp.app/

**Explain why it should be added**
Because the version linked is outdated.

### Issue Checklist

- [x] I have checked for other similar issues
- [x] I have explained why this change is important
- [x] I have added necessary documentation (if appropriate)

**Comment by jaywcjlove** [comment]
@chriszo111 You can open a PR and I will merge it. thx!

**Comment by chriszo111** [comment]
I am not authorised to push to the repository
```
remote: Permission to jaywcjlove/awesome-mac.git denied to chriszo111.
fatal: unable to access 'https://github.com/jaywcjlove/awesome-mac.git/': The requested URL returned error: 403
```

**Comment by jaywcjlove** [comment]
@chriszo111 thx!  I will merge it.
