### ISSUE TITLE
Spark - Fast email client. For both Mac OS and iOS. IS NOT Freeware!!!!

### ISSUE THREAD

**Issue by istarkov** [jaywcjlove/awesome-mac#614]
You can't download Spark without entering billing information at apple store, in no case this application is freeware. As since you provide apple with your credit card you will lose money.

**Comment by ExTEnS10N** [comment]
In some countries, App store don't require to enter any billing info to download a free App. There is an option called "NONE", when app store ask for your billing info. Besides, Apple App store provides many other billing options except for credit card, if you see none of these, perhaps you are not so lucky as we are, I'm sorry to hear that.

**Comment by istarkov** [comment]
Thank you, haven't knew that. Having that text is not free for all, Ill close the issue
