### ISSUE TITLE
Feature suggest: Search and Sort

### ISSUE THREAD

**Issue by ExTEnS10N** [jaywcjlove/awesome-mac#619]
Why there is no search function for such a long list, and why there isn't any time info provides to sort out which app is recently added?
These basic functions are even absent in the new "Awesome Mac App for macOS", what a useless app it is!
By the way, you shouldn't include "amacTests.xctest" when packaging that App, which showing that you start to learn and coding in a hurry, without learning developing macOS/iOS App SYSTEMATICALLY.

**Comment by jaywcjlove** [comment]
@ExTEnS10N 
[amac](https://github.com/jaywcjlove/amac) 应用是一个 React Native for mac，我只学习了一些基础的 Swift，为探索开发 HTTP server，目前还没有精力去完善 Mac 应用。

如果你有兴趣可以 PR 改善应用，或者 自己建一个仓库完善自己的想法，如果你干的不错，我将把你的应用贴在文档的前面进行推广。
