### ISSUE TITLE
Add Azure Data Studio

### ISSUE THREAD

**Issue by george-haddad** [jaywcjlove/awesome-mac#625]
NOTE: Each discrete (stand-alone) request should be in its own issue.

**Put "Add ____" as Title**
 [x] Done

**Provide a link to the proposed addition.**
https://docs.microsoft.com/en-us/sql/azure-data-studio/

**Explain why it should be added**
It should be added to the list as a Free tool that allows a user to connect to a MSSQL server on the MacOS. It also has extensions to connect to PostgreSQL servers. When looking for a good tool that can connect to MSSQL servers all that could be found are tools that were paid. This is a good free alternative that focuses on MSSQL server.

**Additional context**
It has a nice charting feature too.

### Issue Checklist

Put an x in the boxes once you've completed each step. You can also fill these out after creating the issue. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before responding to the issue.

- [x] I have checked for other similar issues
- [x] I have explained why this change is important
- [x] I have added necessary documentation (if appropriate)

**Comment by xcv58** [comment]
Could you please create a PR?

**Comment by george-haddad** [comment]
Sure thing

**Comment by george-haddad** [comment]
PR created #626

**Comment by xcv58** [comment]
Thanks @george-haddad
