### ISSUE TITLE
Add Pencil2D

### ISSUE THREAD

**Issue by hazar-e** [jaywcjlove/awesome-mac#629]
NOTE: Each discrete (stand-alone) request should be in its own issue.

**Put "Add ____" as Title**
 [ x] Done

**Provide a link to the proposed addition.**
https://www.pencil2d.org/

**Explain why it should be added**
An easy, intuitive tool to make 2D hand-drawn animations.

**Comment by jaywcjlove** [comment]
@hazar-e thx!
