### ISSUE TITLE
amac.app is damaged and can't be opened

### ISSUE THREAD

**Issue by petersamokhin** [jaywcjlove/awesome-mac#636]
**Describe the bug**
amac.app is damaged and can't be opened

**To Reproduce**
Download it from [releases](https://github.com/jaywcjlove/amac/releases).

**Expected behavior**
Hmm, idk, maybe it should work ;)

**Screenshots**
![image](https://user-images.githubusercontent.com/20628184/61532606-fb236b80-aa32-11e9-83ca-7d352187d86c.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.5 (18F132)
 - MacBook Pro mid 2017

**Comment by jaywcjlove** [comment]
@petersamokhin Try using the Safari browser to download.

**Comment by jaywcjlove** [comment]
@petersamokhin https://github.com/jaywcjlove/amac/issues/5 Or try this question to help you solve the problem.

**Comment by petersamokhin** [comment]
Okay, sorry, I tried to search issues by «damaged» keyword and missed this.
