### ISSUE TITLE
srocket 凭什么四星推荐？

### ISSUE THREAD

**Issue by yihouzenmeban** [jaywcjlove/awesome-mac#64]
作者弄的这个清单挺好的。。但是看到这么一个不知名的 SS 服务器提供商获得四星推荐。。让人实在不大信服。

连主页显示的已有 1388GB 流量通过本站加速都是填的假数据。。

既然 Manio 想要进入榜单需要进行投票。。那么请问为什么 srocket 直接以四星推荐的姿态进入了科学上网栏目的榜首。。我记得前阵子科学上网那一栏还是没有 srocket  的。。

或者是我孤陋寡闻了。。srocket  是一个很知名的东西，我没听过？

**Comment by jaywcjlove** [comment]
已经放到最下面来，并移除了推荐，欢迎继续指出问题，谢谢！

**Comment by jp1017** [comment]
良心 :+1:
