### ISSUE TITLE
Add  QuickLook Plugins List

### ISSUE THREAD

**Issue by gamtiq** [jaywcjlove/awesome-mac#640]
**Put "Add ____" as Title**
 [X] Done

**Provide a link to the proposed addition.**
http://www.quicklookplugins.com/

**Explain why it should be added**
Currently QuickLook Plugins section contains the only item.
The proposed list is a dedicated place to find plugins for QuickLook.

**Additional context**
The list is a directory of Quick Look Plugins for Apple's OS X.

### Issue Checklist

Put an x in the boxes once you've completed each step. You can also fill these out after creating the issue. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before responding to the issue.

- [X] I have checked for other similar issues
- [X] I have explained why this change is important
- [X] I have added necessary documentation (if appropriate)

**Comment by alichtman** [comment]
Should be merged with #639
