### ISSUE TITLE
Add iZip

### ISSUE THREAD

**Issue by gamtiq** [jaywcjlove/awesome-mac#645]
**Put "Add ____" as Title**
 [X] Done

**Provide a link to the proposed addition.**
https://www.izip.com/

**Explain why it should be added**
It is a free utility to manage ZIP, ZIPX, RAR, TAR, 7ZIP and other compressed files on Mac that is available in App Store.

**Additional context**

### Issue Checklist
Screenshots:
![iZip main screen](https://www.izip.com/images/start.png)
![The new archive assistant](https://www.izip.com/images/newcrypto.png)
![Archive files as removable storage](https://www.izip.com/images/finder.png)

Put an x in the boxes once you've completed each step. You can also fill these out after creating the issue. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before responding to the issue.

- [X] I have checked for other similar issues
- [X] I have explained why this change is important
- [X] I have added necessary documentation (if appropriate)

**Comment by alichtman** [comment]
We have the `Unarchiver` already, and this software looks pretty sketchy to me. I certainly wouldn't use this...
