### ISSUE TITLE
发现两款良心的国产免费mac端的app,在App Store里可以直接下载的

### ISSUE THREAD

**Issue by BigLight-H** [jaywcjlove/awesome-mac#649]
“自动切换输入法”功能：
1.自动切换输入法：支持所有常用输入法，能够根据当前正在运行的不同的应用程序，自动切换对应的输入法，免去人工手动切换；
2.设置切换输入法快捷键：可设置快捷键，在特定情况下，一步切换到指定切换输入法。

Better Menubar让您的Mac状况一目了然，实时监测Mac主要硬件状态。
Better Menubar功能：
Better Menubar能实时显示您的Mac电脑CPU，内存，电池，网络信息。还能显示Mac电脑所连接的Airpods，Magic mouse ，触控板的电量，并可实现快速连接蓝牙设备。

**Comment by jaywcjlove** [comment]
@BigLight-H 请按照模板推荐 软件，或者提交 PR，谢谢！
