### ISSUE TITLE
"Markdown tools" section anchor does not work in website

### ISSUE THREAD

**Issue by eliamaino-fp** [jaywcjlove/awesome-mac#654]
NOTE: Each discrete (stand-alone) request should be in its own issue.

**Describe the bug**
In the deployed website the anchor link for "Markdown Tools" doesn't take you to the right section.

This is due to the fact that the section title has the _awesome_ icon as part of its text, and that icon is taken into account when the `h4` id is generated.

**To Reproduce**
1. Go to https://wangchujiang.com/awesome-mac/
2. Click on "Markdown Tools" (https://wangchujiang.com/awesome-mac/#markdown-tools-)
3. Nothing happens

**Expected behavior**
The page scrolls to the "Markdown Tools" section

**Screenshots**
![Screen Shot 2019-08-28 at 16 58 20](https://user-images.githubusercontent.com/25059869/63867470-2e9fd100-c9b5-11e9-8bd8-270eeda498ae.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.5
 - Browser: Chrome 76, Firefox 68
 - Website

**Comment by jaywcjlove** [comment]
@eliamaino-fp thx!
