### ISSUE TITLE
Add more Office apps

### ISSUE THREAD

**Issue by Drovosek01** [jaywcjlove/awesome-mac#659]
NOTE: Each discrete (stand-alone) request should be in its own issue.

**Put "Add ____" as Title**
- [x] Done

**Provide a link to the proposed addition.**
Pages https://apps.apple.com/app/pages/id409201541?mt=12
Keynote https://apps.apple.com/app/keynote/id409183694?mt=12
Numbers https://apps.apple.com/app/numbers/id409203825?mt=12
iBooks Author https://apps.apple.com/app/ibooks-author/id490152466?mt=12
(More there: https://apps.apple.com/developer/apple/id284417353?mt=12#see-all/mac-apps)

Microsoft Office https://www.apple.com/search/office?page=1&sel=accessories&f=software#!&f=software&fh=4649

**Explain why it should be added**
In macOS, not only designers, musicians or programmers work, but also people with other professions. Sometimes on a computer you need to type a document or presentation or calculate something in tables.
For such tasks, there are free programs that Apple itself provides.
There is also a package of office programs from Microsoft, which is very convenient for those who previously worked with documents in Windows.
The issue of functionality is a separate issue that everyone can decide for himself, but I think the presence of these programs on your list will not harm anyone.
Thsnk you.

### Issue Checklist

Put an x in the boxes once you've completed each step. You can also fill these out after creating the issue. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before responding to the issue.

- [x] I have checked for other similar issues
- [x] I have explained why this change is important
- [x] I have added necessary documentation (if appropriate)

**Comment by jaywcjlove** [comment]
@Drovosek01 thx!
