### ISSUE TITLE
Add Rectangle

### ISSUE THREAD

**Issue by switowski** [jaywcjlove/awesome-mac#702]
NOTE: Each discrete (stand-alone) request should be in its own issue.

**Put "Add ____" as Title**
 [x] Done

**Provide a link to the proposed addition.**
https://rectangleapp.com/

**Explain why it should be added**
[Spectacle app](https://www.spectacleapp.com/) is no longer actively maintained. The author of the Spectacle is recommending Rectangle as a replacement.

**Additional context**

### Issue Checklist

Put an x in the boxes once you've completed each step. You can also fill these out after creating the issue. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before responding to the issue.

- [x] I have checked for other similar issues
- [x] I have explained why this change is important
- [x] I have added necessary documentation (if appropriate)

**Comment by einverne** [comment]
It seems Rectangle has been added. So this issue should be closed now.

**Comment by jaywcjlove** [comment]
@einverne thx!  @switowski thx!
