### ISSUE TITLE
Add Bob

### ISSUE THREAD

**Issue by ripperhe** [jaywcjlove/awesome-mac#714]
NOTE: Each discrete (stand-alone) request should be in its own issue.

**Put "Add ____" as Title**
 [x] Done

**Provide a link to the proposed addition.**
https://github.com/ripperhe/Bob

**Explain why it should be added**
An app that supports screenshot translation and selection translation. The translation source supports Baidu translation, Youdao translation and Google translation

**Additional context**

| Light | Dark |
| :---: | :---: |
| ![Jietu20191228-181341](https://user-images.githubusercontent.com/13943595/71542161-e3ff8700-299d-11ea-981f-ba3d4719b6ab.png) | ![Jietu20191228-181412](https://user-images.githubusercontent.com/13943595/71542165-e661e100-299d-11ea-961f-e38873274116.png) |

### Issue Checklist

Put an x in the boxes once you've completed each step. You can also fill these out after creating the issue. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before responding to the issue.

- [x] I have checked for other similar issues
- [x] I have explained why this change is important
- [x] I have added necessary documentation (if appropriate)

**Comment by Qifull** [comment]
@jaywcjlove This issue has been resolved. Could you please close it?
Thanks!
