### ISSUE TITLE
Chrome链接失效，点开404

### ISSUE THREAD

**Issue by Gayhubonhere** [jaywcjlove/awesome-mac#717]
NOTE: Each discrete (stand-alone) request should be in its own issue.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Browser [e.g. Firefox, Chrome, Safari]
 - Version and Build [e.g. 59.0.2 (64-bit)]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jaywcjlove** [comment]
@Gayhubonhere 不明白什么意思
