### ISSUE TITLE
Remove Stellar Data Recovery

### ISSUE THREAD

**Issue by capnslipp** [jaywcjlove/awesome-mac#728]
NOTE: Each discrete (stand-alone) request should be in its own issue.

**Put "Remove ____" as Title**
 [X] Done

**Explain why it should be removed**

Stellar Data Recovery is a horrible mess of an app.  It's really slow, taking days or weeks to scan a 512 GB drive, the UI completely locks up whenever it's doing any scanning — not updating the progress bar or estimated time at all and showing up as a “Not Responding” app in the Dock — or even expanding a folder in the search results.  It gobbles up double-digit GBs of RAM, making it nearly unusable on a Mac with 8GB of RAM.  And it breaks many many macOS App Design Guidelines.

**Additional context**
Stellar appears to be a poorly-written Qt app, ported to macOS with minimal thought or effort.  It's a headache to use — both through direct interaction and because of how incredibly optimized the app is — and is the very essence of a Anti-Awesome Mac app.  It's a black mark on this list of otherwise excellent apps.

**Comment by jaywcjlove** [comment]
@capnslipp thx!
