### ISSUE TITLE
刚写好的 HammerSpoon 配置文件，关于窗口管理

### ISSUE THREAD

**Issue by S1ngS1ng** [jaywcjlove/awesome-mac#75]
@jaywcjlove 如果觉得好用的话，就加到文档里吧 😃 
链接：https://github.com/S1ngS1ng/HammerSpoon
Repo 里面有 GIF 图片示例

**Comment by jaywcjlove** [comment]
可以来个 PR  😄 好像很酷的样子， GIF快捷键显示是你怎么弄上去的呢？

**Comment by S1ngS1ng** [comment]
好。我搞个PR吧。直接加到HammerSpoon底下可以么？
快捷键展示用的是 KeyCastr，开源项目，要不要也加进来？

**Comment by jaywcjlove** [comment]
😄  KeyCastr 加进来吧，；没有找到这类工具，我正准备开发 一个呢，开发到一半，看来不用浪费时间了。我是把工具放到控制面板中... 进行设置....

![image](https://cloud.githubusercontent.com/assets/1680273/17268274/c236f46c-5658-11e6-996d-2d2f709144a9.png)

**Comment by S1ngS1ng** [comment]
好厉害！！！服！ 😂 
我现在配置完的功能就那些了。。要是有兴趣的话你可以试试哈。顺便提些意见和建议。
大部分类似的还有一个移动窗口的功能，可以加，不过我自己不需要，所以没加。。
还有一个功能就是快速切换程序。。其实也可以加进来，这俩功能都不麻烦

**Comment by jaywcjlove** [comment]
@S1ngS1ng 有空我尝试玩儿玩儿..

**Comment by xcv58** [comment]
我觉得把配置文件直接放进来不是特别合适。因为这样太有利于早期的维护者，以后有别人开发了更好的配置反而出现的难度加大了。

因为配置文件这类东西个人的偏好太重要了，主观因素的成分太多。如果将来出现很多个优秀的配置文件也不方便管理。

我建议单独开一个 repo 收集各种 HammerSpoon 的配置。或者找一下有没有现成的 repo 然后链接过去。

像 Emacs, Vim 之类的 App 我也推荐这样做。@jaywcjlove 你有什么意见？

**Comment by jaywcjlove** [comment]
@xcv58 我觉得可以

**Comment by S1ngS1ng** [comment]
@xcv58 嗯嗯。好的。那我就不链接进来啦

**Comment by alichtman** [comment]
I agree with not having config files in this repo. Hammerspoon is linked, but I don't think we should link this. Closing for now.
