### ISSUE TITLE
关于英文版的一点建议

### ISSUE THREAD

**Issue by S1ngS1ng** [jaywcjlove/awesome-mac#76]
首先，两个版本里，每行最后的那个 SVG 图标都特别小。

不如换成UNICODE 的 Emoji？Emoji 图标不少，足够用，而且不会存在显示问题。比如“免费”可以换成💸  🆓 ，或者也可以标注上收费的为💲 。 “推荐” 可选的就更多， 💯 👍 ❤️ 😍 ⭐ 🌟 ，“热门”可以用 🔥 。但关键是，热门、必备、推荐，这些的判断标准是什么？

另外，在英文版里就不要用（荐）了吧。感觉不够直观。

英文的貌似还没弄完。。我周末有空了可以弄一下，到时发个 PR。@jaywcjlove 到时你看如果合适的话就merge吧。然后科学上网那些，英文版的可以去掉，哈 😂 

还有就是字典那里。。感觉 Mac 自带的已经足够用了，而且用起来也方便，集成性好

**Comment by jaywcjlove** [comment]
科学上网其实是一个vpn 工具，歪国人也需求的哦😂。

Emoji图标太大。尝试排版过，但是不太漂亮。`Emoji`图标在`Github`中气势也是一张图片，我的图片也是放在`Github`的`gh-page`静态服务中。其实效果一样

热门、必备、推荐是我个人主观上的意见，和一些RP的推荐。
如果你对一些推荐有想法 可以开个[issue](https://github.com/jaywcjlove/awesome-mac/issues)进行投票或者讨论 例如这种方法 #55

**Comment by S1ngS1ng** [comment]
嗯嗯。。是VPN的工具。。但是就不需要翻译成科学上网了。哈。毕竟没有墙。

Emoji图标可能会略大。下午在公司看的时候就看不清楚，，因为显示器分辨率低吧。回家在高分辨率的上看还行，能看清~那就这样吧

我这周末试着把没翻译完的翻译完。。不过不能保证完成额-。-

**Comment by jaywcjlove** [comment]
@S1ngS1ng  英文版没有翻译成科学上网是叫`Proxy and VPN Tools`， Retina屏幕看是很舒服的。10～18px  大小我都是试过，这个大小刚好合适。😂

**Comment by S1ngS1ng** [comment]
嗯嗯。。确实应该这么翻译。。另外，我觉得，Utilities那里好像也可以再细分分类。我可以试着搞一下。
还有就是，黑名单，盗版之类的，我觉得就没必要放到英文文档里了吧。你觉得呢？

至少从我周围人看来，没什么人愿意去下盗版，首先是买软件或者学习资料，公司会给报销，大部分IT公司都会这样。其次是一般开源的也有很多选择，绝大部分情况下是不需要去下盗版的

**Comment by jaywcjlove** [comment]
@S1ngS1ng 黑名单，是黑名单的意思，并不是告诉你地址让你去下载的地方，
是你开发了什么软件，到这些网站上看看，进行维权... 比如要求中止提供盗版下载...

**Comment by jaywcjlove** [comment]
慢慢软件多了可以细分的。

**Comment by S1ngS1ng** [comment]
嗯嗯。。好的哈
