### ISSUE TITLE
Remove Fu

### ISSUE THREAD

**Issue by brandonjp** [jaywcjlove/awesome-mac#774]
**Explain why it should be removed**
According to the linked Github page https://github.com/klesh/fu#macos there is no version available for MacOS

**Additional context**
![PixelSnap 2020-04-21 at 12 48 39@2x](https://user-images.githubusercontent.com/199599/79896838-794fdc80-83ce-11ea-9c96-a439eecf7f0b.png)

**Comment by jaywcjlove** [comment]
@brandonjp thx!
