### ISSUE TITLE
Remove Localname

### ISSUE THREAD

**Issue by kant** [jaywcjlove/awesome-mac#776]
NOTE: Each discrete (stand-alone) request should be in its own issue.

**Put "Remove ____" as Title**
 [x] Done

**Explain why it should be removed**
Localname (on line 252) seems to be in deprecated mode. check this http://localname.io/ more than 5 fives in 5 different days and resulted in one page that shows off-topic or no related with the original project.

**Additional context**
There is no additional data to offer

**Comment by heldev** [comment]
Thank you
