### ISSUE TITLE
Add youtube-dl 

### ISSUE THREAD

**Issue by HelperInCa** [jaywcjlove/awesome-mac#781]
NOTE: Each discrete (stand-alone) request should be in its own issue.

**Put "Add ____" as Title**
 [x] Done

**Provide a link to the proposed addition.**

https://github.com/ytdl-org/youtube-dl

**Explain why it should be added**
download videos from YouTube and a few [more sites](http://ytdl-org.github.io/youtube-dl/supportedsites.html).
I think it is more powerful than you-get, and some other video players like IINA use it as default.

**Additional context**

### Issue Checklist

Put an x in the boxes once you've completed each step. You can also fill these out after creating the issue. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before responding to the issue.

- [x] I have checked for other similar issues
- [x] I have explained why this change is important
- [x] I have added necessary documentation (if appropriate)

**Comment by jaywcjlove** [comment]
https://github.com/jaywcjlove/awesome-mac/blob/85a20e4aa6eafef72e044f9ec9e8bba694d63c47/README.md?plain=1#L738
