### ISSUE TITLE
关于添加了盗版网站链接的初衷和想法

### ISSUE THREAD

**Issue by jaywcjlove** [jaywcjlove/awesome-mac#79]
对于盗版软件下载，在我出来工作开始接触使用电脑的时候，几乎我的`windows`系统里面90%全是盗版软件，哪个时候没有罪恶感，一种理所应当，还觉得使用盗版软件很屌的，还帮助人家安装盗版软件，装盗版系统。

在零几年的时候，有一次我去面试，我本是一个撸ps的web设计师，去面试人家玩儿得比较高端，使用苹果电脑做设计，设计师清一色的苹果电脑，我第一次听说苹果电脑，连ps的菜单都找不到在哪儿，甚至不知道在怎么开机，我把那台看上像按钮的地方全部摁了一遍，那是一台08年新款的iMac，开机按钮在屁股后面...，我想亲一下它的屁股。

很显然这次受挫折了，漂亮简洁的台式机，和简单的图形操作界面深深的吸引了我，用了Mac系统完全不想用windows系统，决定搞台Mac电脑然后学会使用它，我在接下来的两年里，不停的申请信用卡，攒钱，每周去两次苹果店去体验它，我爱上它了。在后来我拥有它之后，我如愿的完成了我的“梦想” ，发现软件并不好找，盗版软件并不能像windows那么好找。在我大天朝，使用和分享盗版软件这种犯罪成本极低，而且也没有人管，开始有了一些想法，创办了一个下载盗版Mac程序的网站，`www.pc175.com`，取名电脑一起玩，这个域名是我创业失败留下的一个域名，顺手就用Discuz搭建起来了，还准备给它开发一个盗版的软件下载市场（这个应用开发了一点点就结束了[序源码在这里](https://github.com/jaywcjlove/appstore)），那个时候Mac上面还没有App store，我想用它分享一些软件，而且有不少人觉得这个点子非常好，到后面经常有一千多人同时在线。这个时候一样使用盗版软件是一种理所应当的事儿。

在我尝试开发Mac应用的时候，需要分发这些免费小应用，发现一些网站连我的网站都不挂，我表示很生气免费的网站都不挂，太过分了。重新思考我这是挂个自己的网站，他们都这样，那写开发收费应用的人会怎么想呢？这个时候我就想把我的网站关闭了，刚好我大天朝做论坛还要到局子里面拍照备案，于是我下定决心把网站给关闭了。

利用我自己的技术棧实现了一些小玩意儿
- [App store](http://mac.xunlei.com/app/soft/details.php?soft_id=160) 放弃了。
- 中国农历 for Mac [放在Macx里面的](http://macx.cn/thread-2137402-1-1.html) [放在威锋网上的](http://bbs.feng.com/read-htm-tid-4493892.html)有上百万的下载量。
- [唐僧舅舅](https://tangseng99.com) 风险太大关闭了，和同事 @liujianping 一起开发的
- ....

后面打包了一堆Mac 的 WebApp。在这个过程中，玩上了Github，搜集了一些软件，发现并非所有的软件都收费，有很多收费软件都有免费的替代品，还有很多软件都开源呢，本着自己是一个开发者，有些能力购买软件，还可以找一些免费开源的Mac应用，甚至自己开发应用，所以主动劝大家不购买、不使用，不传播盗版软件，让我们能使用到更多更好的Mac软件，刚好我的公众账号获得微信的“原创声明功能”，我实验一下回复功能，发了一篇爆火的文章《[工具武装的前端开发工程师](http://mp.weixin.qq.com/s?__biz=MzAwNzgxMjYzMA==&mid=2649129466&idx=1&sn=e50f0049b096cf28b7cf707a4b5adb33#rd)》，我又建立这样一个仓库来持续更新作为补充，我把我平时搜集应用发现的一些盗版软件下载网站，作为黑名单放到了我这个资源清单中，因为这个仓库持续在 Github 趋势榜上，一度爬到了第一的位置，所以有了影响力之后，只想传授一些正能量，提醒你在这些地方下载应用有风险，让开发者的心血付之东流，这样未来就没有更好的Mac应用玩儿了。

我把我平时搜集应用发现的一些盗版软件下载网站，作为黑名单放到了我这个资源清单中，起初只是想，我无法像`pc175.com`那样关闭网站，提醒你在这些地方下载应用有风险，让开发者的心血付之东流，未来没有更好的Mac应用玩儿了，后面我们在这里讨论过了 #17 。
## 作用

挂盗版软件下载网站的黑名单，你可以：
1. 在这些网站中找到你的软件进行`维权`
2. `提示`你这些网站下载软件有风险
3. 我反对盗版的`态度`
4. `抵制`他们，让我们的Mac有更多好用的软件（Mac上软件少众所周知）

确实有引流的作用，我认为现在维权意识越来越强，我将盗版软件下载网站列出来，就像 @xcv58 所说的有警示作用，给予这些网站的所有者压力，当参与开发翻墙工具的时候，软件使用人多了压力好大，随时感觉要进局子一样，于是关闭了，码字到此结束。我们可以在 #17 中参与继续讨论《是否删除盗版软件下载网站的清单》这个问题。

最后劝大家不购买、不使用，不传播盗版软件。

**Comment by xcv58** [comment]
看完非常感动！我小时候也是有盗版软件必用，现在几乎不用盗版软件了。

盗版问题是个很大的问题，牵涉到很多开发者的利益，使用者的便利、用户体验甚至财产安全。但正视问题是第一步，如果不承认有分发推广盗版软件的网站肯定不是解决盗版问题的好方法。解决盗版问题很多利益相关方都在努力。譬如开发者用订阅取代销售软件，无限期试用替代限制功能。用户的自觉抵制与推广正版。组织正规的团购降低售价。

据我所知不愿意付费购买正版软件的人差不多有两种因素：钱和观念。现在钱基本上不会太缺了，哪怕是 Parallels 那种一年一收费的软件大多数人都买得起（愿不愿意就两说了）。所以现在观念的作用就更大了。在推广正版软件的同时告诉别人有哪些网站是盗版软件的集中地可以起到辅助作用。

**Comment by yfgeek** [comment]
挺作者的行为，不过，似乎把地址贴出来是不是起到了反作用，反而更多的人直接去点击了下面的下载地址

**Comment by xcv58** [comment]
@yfgeek 请在 #17 中讨论。我支持的理由已经写到那里了

**Comment by jaywcjlove** [comment]
@yfgeek 这个人理解， 美国人人可持枪，可中国禁刀，还是没有用

即使引流了也没有关系，如果被人关注了会有压力的，维权的路上你知道要找谁维权，哪些网站侵犯了你的权利...

我们抵制，不是掩耳盗铃，视而不见。

**Comment by yfgeek** [comment]
@jaywcjlove 有一定道理

**Comment by jaywcjlove** [comment]
@yfgeek 在我大天朝，已经习惯，一刀切，“禁用”的方式，  我希望他们开始自省，然后提供合法免费的软件😄，如自研，优惠....  而不是盗版，

什么时候开始能自省呢，当各大软件厂商都关注到它，当维权者关注到它.....😂😂😂

**Comment by Mr-Binary** [comment]
这个也只有我们IT从业者才能理解，其他人还是限于国情。但是毕竟能改变一点是一点。
