### ISSUE TITLE
Add Boop

### ISSUE THREAD

**Issue by abhi21git** [jaywcjlove/awesome-mac#802]
**Put "Add Boop" as Title**
 - [x] Done

**Provide a link to the proposed addition.**
[https://boop.okat.best/](https://boop.okat.best/)

**Explain why it should be added**
It's a smile snippet tool that provides various functionalities like JSON formatting, MD5 Checksum, reverse string, encode, and much more.

**Additional context**
<img width="663" alt="UI" src="https://user-images.githubusercontent.com/42537316/87385436-b1c11a00-c5bb-11ea-850b-75e7dc1cdac2.png">

### Issue Checklist
- [x] I have checked for other similar issues
- [x] I have explained why this change is important
- [x] I have added necessary documentation (if appropriate)

**Comment by ColoursofOSINT** [comment]
Close @jaywcjlove .
