### ISSUE TITLE
Add Visual Studio Code to the list of IDEs

### ISSUE THREAD

**Issue by mayavera** [jaywcjlove/awesome-mac#838]
**Put "Add ____" as Title**
- [x] Done

**Provide a link to the proposed addition.**
https://code.visualstudio.com/

**Explain why it should be added**
Visual Studio code is a free, powerful, and extremely popular IDE for a ton of languages. I use it daily for web development and have used it in the past for Go and Rust development. It works great on Macs and I'd recommend it to any developer!

**Additional context**
<img width="642" alt="Screen Shot 2020-11-12 at 12 02 29 PM" src="https://user-images.githubusercontent.com/5532165/98971302-f5328300-24de-11eb-945d-0c64a6a3dc8d.png">

### Issue Checklist

Put an x in the boxes once you've completed each step. You can also fill these out after creating the issue. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before responding to the issue.

- [x] I have checked for other similar issues
- [x] I have explained why this change is important
- [x] I have added necessary documentation (if appropriate)

**Comment by jaywcjlove** [comment]
@mayavera thx!
