### ISSUE TITLE
建议把 Atom 插件换成 Awesome Atom

### ISSUE THREAD

**Issue by xcv58** [jaywcjlove/awesome-mac#84]
和我在 #76 里说的理由一样，没有必要自己维护一个插件列表。

[Awesome Atom](https://github.com/mehcode/awesome-atom) 已经有 91 个 commits, 510 个 stars. 而且插件都有分类和截图。

唯一的缺点就是没有中文版。

**Comment by xcv58** [comment]
这个 https://github.com/kompasim/atom-plugins 是中文版的。

**Comment by jaywcjlove** [comment]
@xcv58  所以我们这里只是top 10或者20 不能多了，常用著名的plug，例如Emmet N个软件有这个插件。

搜集太多，这样还不如上[atom plugins](https://atom.io/packages)官网，查看趋势榜

**Comment by xcv58** [comment]
@jaywcjlove 这就是我推荐链接到这种仓库的原因。因为 Top K 的方式总会有缺的，或者有争议。干脆链接到一个专门做这事的仓库上。这样咱们可以免去维护这些插件列表的麻烦。

我个人用 Atom 的经验，基本上必装的插件就有将近 20 个。这还是去掉语言相关的插件之后的数量。

**Comment by jaywcjlove** [comment]
@xcv58 后面看看用什么形式展现吧。

**Comment by lixinliang** [comment]
推荐一个atom插件..  
https://atom.io/packages/tree-view-search-bar
也是我自己写的，希望有更多的人用~
主要功能是在tree-view上快速查找文件用的。

**Comment by xcv58** [comment]
@lixinliang 刚才试用了一下，感觉还不错。建议你自己加上中文双语的提个 PR @jaywcjlove 应该会 Merge 的。

**Comment by alichtman** [comment]
Closing this as it looks like changes have been merged to master already.
