### ISSUE TITLE
Add Does It ARM Apple Silicon App Test

### ISSUE THREAD

**Issue by ThatGuySam** [jaywcjlove/awesome-mac#873]
This is a tool I built so people can test app compatibility with Apple Silicon without owning an actual Apple Silicon or Apple M1 Mac. 

It isn't a Mac App but I feel like it could be a critical tool for Apple SIlicon Mac users but it may exactly fit in the main app list. 

Let me know what you think. 

Here's the info for what it's worth: 

**Put "Add ____" as Title**
- [x] Done

**Provide a link to the proposed addition.**
https://doesitarm.com/apple-silicon-app-test/

**Explain why it should be added**
So Mac users considering buying a new Apple SIlicon or Apple M1 Mac can test specific apps from their current mac to confirm compatibility. 

**Additional context**
This browser-based tool is part of an open-source project dedicated to reporting App Compatibility for Apple Silicon Macs

### Issue Checklist

- [x] I have checked for other similar issues
- [x] I have explained why this change is important
- [x] I have added necessary documentation (if appropriate)

**Comment by xcv58** [comment]
Hi @ThatGuySam,

Thanks for reaching out. For this project, there are two parts:

1. The github1s.com itself
2. Development of this project

For 1. I tested with M1 MacBook and it works well. And I don't think we need any additional check for ARM Apple Silicon with the web application itself since it's a pure web application.

For 2, we are blocked by this https://github.com/microsoft/playwright/issues/5443 which fails the VS Code build. Does the https://doesitarm.com/apple-silicon-app-test/ help to check whether it passes development process?

**Comment by ThatGuySam** [comment]
@xcv58 Was your original comment about testing all the apps listed?

**Comment by xcv58** [comment]
> @xcv58 Was your original comment about testing all the apps listed?

No, I thought it's for a different repo. 

I think it's a good tool to be included in this repo, what category do you think it fits?

**Comment by ThatGuySam** [comment]
One option could be Utilities > System Related Tools

Another could be to list doesitarm.com under "Mac App Download Sites" (Since it does link to download pages) and then mention the tool as a note nested under the line for doesitarm.com

I want to make sure I respect the layout of the list as much as possible.

**Comment by xcv58** [comment]
I suggest we add it to `Utilities > System Related Tools`.

**Comment by ThatGuySam** [comment]
Sounds good! 

Do you need me to make a PR?

**Comment by xcv58** [comment]
> Sounds good!
> 
> Do you need me to make a PR?

Yes please make a PR if you would like do it. Thanks!

**Comment by ThatGuySam** [comment]
PR added! #874

**Comment by xcv58** [comment]
Thank you @ThatGuySam 🙏
