### ISSUE TITLE
Remove OpenOffice

### ISSUE THREAD

**Issue by philippw** [jaywcjlove/awesome-mac#885]
NOTE: Each discrete (stand-alone) request should be in its own issue.

**Put "Remove ____" as Title**
 [X] Done

**Explain why it should be removed**
[Apache Open Office](https://blogs.apache.org/OOo/) has long only seen rudimentary bug fix releases. Mostly concerned with minor updates to keep it working on newer OS releases.
It hasn't seen a major release since 2014 (7 years ago) and [major security vulnerabilities](https://www.cvedetails.com/vulnerability-list/vendor_id-1510/Openoffice.html) have gone unfixed for a long time.

See the [Open Letter to Apache OpenOffice ](https://blog.documentfoundation.org/blog/2020/10/12/open-letter-to-apache-openoffice/) for more information.

**Additional context**
Alternatively, one could redirect users looking for Apache OpenOffice to LibreOffice, referencing the above blog post.

**Comment by xcv58** [comment]
I agree with you, do you mind to create a PR to remove it?
