### ISSUE TITLE
Remove Assetizr Duplicate

### ISSUE THREAD

**Issue by mashupmark** [jaywcjlove/awesome-mac#926]
NOTE: Each discrete (stand-alone) request should be in its own issue.

**Put "Remove ____" as Title**
 [x] Done

**Explain why it should be removed**
A clear and concise description of why it should be added to this list.

The Tool „Assetizr“ is listed twice in the readme under Design and Product > Other Tools.
One of the two should be removed.

**Comment by jaywcjlove** [comment]
@mashupmark thx!
