### ISSUE TITLE
https://github.com/jaywcjlove/awesome-mac/blob/63d45895afb0e36545fa482d501e354b9f2e960a/README-zh.md#L592

### ISSUE THREAD

**Issue by dontbethatguy209** [jaywcjlove/awesome-mac#933]
NOTE: Each discrete (stand-alone) request should be in its own issue.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Browser [e.g. Firefox, Chrome, Safari]
 - Version and Build [e.g. 59.0.2 (64-bit)]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jaywcjlove** [comment]
@dontbethatguy209  ???? :(
