### ISSUE TITLE
Add UTM

### ISSUE THREAD

**Issue by ThomasWaldmann** [jaywcjlove/awesome-mac#957]
**Put "Add ____" as Title**
- [X] Done

**Provide a link to the proposed addition.**
https://mac.getutm.app

**Explain why it should be added**
UTM is an easy-to-use GUI for QEMU and can run ARM64, x64 and other VMs on M1 Macs.

E.g. one can run Debian or Ubuntu Linux (arm64) and Windows 10 Preview (arm64) and it is fast.
One can also run x86-64 VMs (like "normal" Windows), but it will be slower due to emulation.

### Issue Checklist

Put an x in the boxes once you've completed each step. You can also fill these out after creating the issue. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before responding to the issue.

- [X] I have checked for other similar issues
- [X] I have explained why this change is important
- [X] I have added necessary documentation (if appropriate)

**Comment by jaywcjlove** [comment]
@aemi-dev has been added to the list.
