### ISSUE TITLE
Add Rectangle

### ISSUE THREAD

**Issue by kyon45** [jaywcjlove/awesome-mac#969]
[**Rectangle**](https://rectangleapp.com/) is a fancy tool to move and resize widgets.

- [x] Open Source
- [x] Free Software

**Comment by omar-njie** [comment]
HI [kyon45](https://github.com/kyon45), You're definitely right. I use Rectangle every day. It's an awesome tool to use. Though there are other apps that accomplish the same thing, like Magnet, but Rectangle is free and open source.

**Comment by jaywcjlove** [comment]
has been added to the list

https://github.com/jaywcjlove/awesome-mac/blob/a5f53571c0d61c00cae76cfb46f539ddf3febe2c/README.md?plain=1#L971
