### ISSUE TITLE
Please add Magnet

### ISSUE THREAD

**Issue by damengilland** [jaywcjlove/awesome-mac#98]
"Every time you want to copy content from one app to the other, compare files side by side or multitask in any other way, you need all the windows arranged accordingly. Magnet makes this process clean and simple. In just one drag to the edge, you snap any window into left, right, top or bottom half of your screen"
- Magnet on the Mac App Store || https://itunes.apple.com/us/app/magnet/id441258766?mt=12

**Comment by ericbn** [comment]
What alternative do the downvoters recommend? I find [Spectacle](https://spectacleapp.com/) a good open source alternative, but Magnet still has more features, and I would list both.

**Comment by rubenvarela** [comment]
I've been using BetterTouchTool for this (this actually used to be part of BetterSnapTool).

Yet another alternative.

**Comment by jaywcjlove** [comment]
@rubenvarela I would like to use the Chinese and English form of the switch.

**Comment by alichtman** [comment]
All in the list. Closing.
